"""ImageMM: joint multi-frame image restoration and super-resolution.

Implementation of Sukurdeep, Budavári, Connolly & Navarro (2025), "ImageMM: Joint
Multi-Frame Image Restoration and Super-Resolution", arXiv:2501.03002 (v3).
Equation / algorithm numbers refer to the paper; verification against its own
model: experiments/test_imagemm.py.

Data (Sec. 2): n coregistered, background-subtracted exposures y(t) with
per-pixel variances v(t), binary masks m(t) and PSFs f(t) measured from their
stars (prepared from the raw subs by astrophoto/exposures.py).  Model (Eq. 1, 10):

    y(t)_i = (D (h(t) * x))_i + eta(t)_i,    eta(t)_i ~ N(0, v(t)_i),    x >= 0

x is the latent sky (sky = 0, sources > 0), padded so that every exposure pixel
is fully modelled: r(d + d') - 1 pixels per axis for d exposure pixels and PSFs
of d' pixels (d + d' - 1 without super-resolution); "*" is the valid
convolution; D is r x r average pooling and D^T subdivides every entry into
r x r replicas (Algorithm 2 remark).  Without super-resolution h(t) = f(t).

Algorithms 1 / 2 (Eqs. 7-9):

    u_k  = sum_t H(t)^T D^T W(t) y(t) / sum_t H(t)^T D^T W(t) D H(t) x_{k-1},    W(t) = diag(m(t) / v(t))
    u'_k = max(1/kappa, min(kappa, u_k)),    x_k = x_{k-1} * u'_k

Algorithm 3 (Eqs. 13-18): W(t) becomes m / v * psi(r) with the residuals
r = (y - D H x) / sigma recomputed every iteration and psi(z) = rho'(z)/z of the
Huber loss (Eq. 15, delta = 2).

x0 (Sec. 4.1): the median of the exposures, padded, non-positive values
replaced by a positive one; kappa = 2.  Stop (Appendix C, Eq. C15) when
|(1/M~) sum_i (m~ xi_k)_i - 1| < epsilon with xi_k = u'_k / u'_{k-1} and the
effective mask m~ = [(1/n) sum_t H^T D^T m(t) > mu], mu = 0.1, epsilon in
(1e-6, 1e-4); K is the maximum number of iterations.

Super-resolved PSFs (Eq. 11, Algorithm 2 lines 4-6): h(t) minimises
(1/d') sum_i (f(t)_i - (D(h * g_sigma))_i)^2, unconstrained, by Adam, with g_sigma
a centred Gaussian (2 r d' - 1 pixels per axis) generated by Monte Carlo
integration.

Like the paper (Sec. 5.1), the field is processed in cutouts; here they overlap
and are blended.

Optional, not part of the paper, each implemented to its own reference:
* Biggs & Andrews (1997) vector extrapolation of the multiplicative iteration
  (``BiggsAndrews``);
* seeing groups: inverse-variance coadds of exposures of similar PSF, each a
  single exposure of the same model with the weight-averaged PSF
  (``coadd_groups``);
* Moffat PSF models fitted to the empirical PSFs (exposures.fit_moffat).
"""
from __future__ import annotations

import math
import os
import time

import cv2
import numpy as np
import torch
import torch.nn.functional as F

from .denoise import _edge_weights, pick_device


# ----------------------------------------------------------------- PSFs
def gaussian_psf_mc(sigma: float, size: int, n_samples: int = 200_000_000, seed: int = 0,
                    chunk: int = 10_000_000) -> np.ndarray:
    """g_sigma of Algorithm 2 (line 4): a centred Gaussian PSF with standard deviation
    ``sigma`` (latent pixels) on a size x size grid (size odd), generated by Monte Carlo
    integration: every pixel holds the fraction of samples of N(0, sigma^2 I) that fall
    inside it (pixel j covers [j - c - 1/2, j - c + 1/2) around the centre c)."""
    assert size % 2 == 1
    rng = np.random.default_rng(seed)
    c = size // 2
    counts = np.zeros(size * size, np.int64)
    left = n_samples
    while left > 0:
        k = min(chunk, left)
        ij = np.floor(rng.normal(0.0, sigma, size=(k, 2)) + 0.5).astype(np.int64) + c
        ok = (ij >= 0).all(1) & (ij < size).all(1)
        counts += np.bincount(ij[ok, 0] * size + ij[ok, 1], minlength=size * size)
        left -= k
    g = counts.reshape(size, size).astype(np.float64)
    return (g / g.sum()).astype(np.float32)


def refine_psf(f: np.ndarray, up: int, sigma: float, g: np.ndarray | None = None, rel_tol: float = 1e-6,
               device=None) -> tuple[np.ndarray, float]:
    """Super-resolved PSF h of Eq. 11 (Algorithm 2, line 6):

        h = argmin_{h in R^{r d'}} (1/d') sum_i (f_i - (D(h * g_sigma))_i)^2

    f: target PSF (d' x d', d' odd); h: r d' x r d'; g_sigma: (2 r d' - 1) x (2 r d' - 1);
    "h * g_sigma" is the valid convolution, of r d' x r d' pixels, and D is r x r average
    pooling.  Solved from f subdivided into r x r replicas (``refine_psfs``).

    Eq. 11 has r^2 d'^2 unknowns for d'^2 equations, so its minimisers form an affine
    space, and once the loss is ~0 Adam's normalised steps keep moving h along it.  The
    iteration therefore stops as soon as the mean squared difference is below ``rel_tol``
    x mean(f^2) (the paper reports 3.9e-8 for its HSC PSFs, ~2e-4 relative), which leaves h
    at the minimiser reached from the smooth initial guess.
    Returns (h, final mean squared difference)."""
    h, mse = refine_psfs(f[None], up, sigma, g=g, device=device, rel_tol=rel_tol)
    return h[0], float(mse[0])


def refine_psfs(fs: np.ndarray, up: int, sigma: float, g: np.ndarray | None = None, device=None,
                rel_tol: float = 1e-6, method: str = "fista", max_iters: int = 20_000, nonneg: bool = True,
                stall: float = 1e-2, stall_window: int = 500, chunk: int = 4096, **adam_kw) -> tuple[np.ndarray, np.ndarray]:
    """Eq. 11 (see ``refine_psf``) for many target PSFs at once: fs (N, d', d') -> h (N, r d', r d').

    ``method`` "fista" (default): Eq. 11 is a linear least-squares problem, solved by projected
    accelerated gradient (FISTA, Beck & Teboulle 2009) with the exact step 1/L, L = ||A||^2 <=
    1/r^2 for A h = D(h * g_sigma) (D averages r x r, and convolution with a unit-sum non-negative
    kernel has norm <= 1); the convolution runs through FFTs.  From the same initial guess (f
    subdivided into r x r replicas / r^2) and with the same stopping rule it reaches the same
    fit as Adam, 7-25x faster (IC 405: 300 kernels in 2.3 s vs 59 s at r = 1, 36 s vs 250 s at
    r = 2), which matters once the PSFs vary over the field (a kernel per exposure, channel and
    node of the field grid: ~10^4).  "adam": the paper's optimiser (``_refine_psfs_adam``).

    ``nonneg``: h >= 0 (projection after every step).  Each kernel stops when its mean squared
    difference is below ``rel_tol`` x mean(f^2) (1e-6: 0.1 % rms, below the PSFs' own
    measurement error; the paper reports 3.9e-8 absolute, ~2e-4 relative, for its HSC PSFs), or
    when it fell by less than ``stall`` over ``stall_window`` iterations.
    Returns (h, per-kernel final mean squared difference)."""
    if method == "adam":
        return _refine_psfs_adam(fs, up, sigma, g=g, device=device, rel_tol=rel_tol, nonneg=nonneg, **adam_kw)
    device = device if isinstance(device, torch.device) else pick_device(device or "auto")
    N, n, _ = fs.shape
    m = up * n
    if g is None:
        g = gaussian_psf_mc(sigma, 2 * m - 1)
    Pf = 1 << (3 * m - 3).bit_length()                    # >= full linear convolution size 3m - 2
    G = torch.fft.rfft2(torch.from_numpy(np.ascontiguousarray(g, np.float32)).to(device), s=(Pf, Pf))
    L = 1.0 / (up * up)
    outs, mses = [], []
    for a in range(0, N, chunk):
        ft = torch.from_numpy(np.ascontiguousarray(fs[a:a + chunk], np.float32)).to(device)
        B = ft.shape[0]
        scale = ft.abs().amax(dim=(1, 2)).view(B, 1, 1).clamp_min(1e-30)
        f = ft / scale

        def A(h):                       # D(h * g_sigma), the valid part (output j at full index j + m - 1)
            full = torch.fft.irfft2(torch.fft.rfft2(h, s=(Pf, Pf)) * G, s=(Pf, Pf))
            return pool(full[:, None, m - 1:2 * m - 1, m - 1:2 * m - 1], up)[:, 0]

        def AT(z):                      # its adjoint: D^T (replicas / r^2), then correlation with g_sigma
            zu = unpool(z[:, None], up)[:, 0] / (up * up)
            pad = torch.zeros(B, Pf, Pf, device=device)
            pad[:, m - 1:2 * m - 1, m - 1:2 * m - 1] = zu
            return torch.fft.irfft2(torch.fft.rfft2(pad) * G.conj(), s=(Pf, Pf))[:, :m, :m]

        h = unpool(f[:, None], up)[:, 0] / (up * up)
        if nonneg:
            h = h.clamp_min(0)
        yk, hp, t = h.clone(), h.clone(), 1.0
        target = rel_tol * (f ** 2).mean(dim=(1, 2))
        active = torch.ones(B, dtype=torch.bool, device=device)
        best_prev = torch.full((B,), float("inf"), device=device)
        for it in range(max_iters):
            hn = yk - AT(A(yk) - f) / L
            if nonneg:
                hn = hn.clamp_min(0)
            hn = torch.where(active[:, None, None], hn, hp)      # a stopped kernel stays where it is
            tn = (1 + math.sqrt(1 + 4 * t * t)) / 2
            yk = hn + ((t - 1) / tn) * (hn - hp)
            hp, t = hn, tn
            if it % 50 == 0:
                mse = ((A(hp) - f) ** 2).mean(dim=(1, 2))
                active &= mse >= target
                if it % stall_window == 0:
                    if it > 0:
                        active &= mse < (1 - stall) * best_prev
                    best_prev = mse.clone()
                if not bool(active.any()):
                    break
        mse = ((A(hp) - f) ** 2).mean(dim=(1, 2)) * scale.view(B) ** 2
        outs.append((hp * scale).cpu().numpy().astype(np.float32))
        mses.append(mse.cpu().numpy())
    return np.concatenate(outs), np.concatenate(mses)


def _refine_psfs_adam(fs: np.ndarray, up: int, sigma: float, g: np.ndarray | None = None, lr: float = 1e-3,
                      max_iters: int = 200_000, rel_tol: float = 1e-8, device=None, nonneg: bool = True,
                      stall: float = 1e-2, stall_window: int = 1000) -> tuple[np.ndarray, np.ndarray]:
    """Eq. 11 (see ``refine_psf``) for many target PSFs at once: fs (N, d', d') -> h (N, r d', r d').

    ``nonneg``: h >= 0 (projected Adam: negative entries set to 0 after every step).  h is a PSF,
    and the multiplicative MM update (Eqs. 7-9) is derived for non-negative kernels.  Without the
    constraint, at r = 1 Adam's per-parameter steps drive the directions g_sigma barely constrains
    and leave h oscillating: 24-59 % negative flux even for smooth Moffat PSFs whose exact
    minimiser has 0.2-3 % (experiments/README.md), and ImageMM then ran to its iteration cap.
    ``stall``: a kernel also stops when its loss fell by less than this fraction over the last
    ``stall_window`` iterations (at r = 1 the rel_tol target is usually out of reach).

    The N problems are independent: each kernel's gradient comes only from its own loss and
    Adam's update is per parameter, so solving them together (one grouped convolution) gives
    every kernel exactly the iterates of a solve on its own.  Each kernel stops (is frozen)
    when its own mean squared difference falls below rel_tol x mean(f^2).
    Returns (h, per-kernel final mean squared difference)."""
    device = device if isinstance(device, torch.device) else pick_device(device or "auto")
    N, n, _ = fs.shape
    m = up * n
    if g is None:
        g = gaussian_psf_mc(sigma, 2 * m - 1)
    ft = torch.from_numpy(np.ascontiguousarray(fs, np.float32)).to(device)
    gt = torch.from_numpy(np.ascontiguousarray(g, np.float32)).to(device)[None, None]
    scale = ft.abs().amax(dim=(1, 2)).view(N, 1, 1)
    # Adam's steps are ~lr per parameter; optimising z = h / max|f| makes the step lr * max|f|
    z = (unpool(ft[:, None], up)[:, 0] / up ** 2 / scale).clone().requires_grad_(True)
    opt = torch.optim.Adam([z], lr=lr)
    target = rel_tol * (ft ** 2).mean(dim=(1, 2))
    active = torch.ones(N, dtype=torch.bool, device=device)
    if nonneg:
        with torch.no_grad():
            z.clamp_(min=0)
    best_prev = torch.full((N,), float("inf"), device=device)

    # every kernel correlates the same g_sigma: unfold its m x m patches once (im2col, as conv2d
    # evaluates a convolution) and apply all N flipped kernels as one matrix product
    cols = F.unfold(gt[:, :1], m)[0]                                   # (m^2, m^2) patches of g

    def model(zz):
        conv = ((zz * scale).flip(1, 2).reshape(N, m * m) @ cols).view(1, N, m, m)
        return pool(conv, up)[0]

    for it in range(max_iters):
        per = ((ft - model(z)) ** 2).mean(dim=(1, 2))
        with torch.no_grad():
            active &= per >= target
            if it % stall_window == 0:
                if it > 0:
                    active &= per < (1 - stall) * best_prev      # still improving
                best_prev = per.detach().clone()
        if not bool(active.any()):
            break
        opt.zero_grad()
        (per * active).sum().backward()
        # a frozen kernel must not move at all (Adam would still step on its momentum)
        saved = z.detach()[~active].clone()
        opt.step()
        with torch.no_grad():
            if nonneg:
                z.clamp_(min=0)
            z[~active] = saved
    with torch.no_grad():
        final = ((ft - model(z)) ** 2).mean(dim=(1, 2))
    return (z * scale).detach().cpu().numpy().astype(np.float32), final.cpu().numpy()


def _fwhm(k: np.ndarray) -> float:
    """FWHM of a centred PSF from its half-light radius (exact for a Gaussian)."""
    n = k.shape[-1]
    yy, xx = np.mgrid[:n, :n] - n // 2
    r = np.hypot(yy, xx).ravel()
    o = np.argsort(r)
    c = np.cumsum(k.ravel()[o]) / k.sum()
    return float(2 * r[o][np.searchsorted(c, 0.5)])


# ----------------------------------------------------------------- MM core
def pool(z: torch.Tensor, r: int) -> torch.Tensor:
    """D: r x r average pooling."""
    return z if r == 1 else F.avg_pool2d(z, r)


def unpool(z: torch.Tensor, r: int) -> torch.Tensor:
    """D^T as the paper defines it (Algorithm 2 remark): every entry subdivided into
    r x r replicas."""
    return z if r == 1 else z.repeat_interleave(r, -2).repeat_interleave(r, -1)


def huber_psi(z: torch.Tensor, delta: float) -> torch.Tensor:
    """psi(z) = rho'(z) / z (Eq. 18) of the Huber loss H_delta (Eq. 15): 1 for |z| <= delta,
    delta / |z| otherwise."""
    a = z.abs()
    return torch.where(a <= delta, torch.ones_like(z), delta / a.clamp_min(1e-30))


def latent_shape(h: int, w: int, ks: int, r: int) -> tuple[int, int]:
    """Latent size per axis for d exposure pixels and kernels of ks = r d' latent pixels:
    r(d + d') - 1 (Sec. 4.2; d + d' - 1 for r = 1, Sec. 3.1).  The valid convolution
    with the kernel maps it to r d pixels, which D pools to d."""
    return r * h + ks - 1, r * w + ks - 1


def exposure_origin(ks: int, r: int) -> float:
    """Latent coordinate of the centre of exposure pixel 0; exposure pixel i is centred at
    latent r i + this.  (Output j of the valid convolution is the kernel window centred at
    latent j + (ks - 1)/2, and D averages outputs r i ... r i + r - 1.)"""
    return (ks - 1) / 2 + (r - 1) / 2


def free_device_memory(device: torch.device) -> float | None:
    """Bytes this process can still allocate on ``device`` (None: no limit known, CPU)."""
    if device.type == "cuda":
        free, _ = torch.cuda.mem_get_info(device)
        # memory PyTorch has reserved but not handed out is available to this process too
        return float(free + torch.cuda.memory_reserved(device) - torch.cuda.memory_allocated(device))
    if device.type == "mps":
        try:
            return float(torch.mps.recommended_max_memory() - torch.mps.driver_allocated_memory())
        except Exception:
            return None
    return None


# per exposure, per channel and pixel of a cutout, mm_restore keeps y, v and the mask
# (3 arrays) and, for the exposures of one chunk, about 8 arrays of temporaries (forward
# model, residual, weights, their products, the im2col band buffers)
_PERSISTENT, _PER_CHUNK = 3, 8


def auto_chunk(n: int, C: int, d: int, device: torch.device, reserve: float = 0.85) -> int:
    """Exposures per chunk so that the temporaries of one chunk fit next to the persistent
    arrays.  The chunking only changes the order of the sums over exposures."""
    free = free_device_memory(device)
    if free is None:
        return n
    per = C * d * d * 4
    avail = reserve * free
    return int(max(1, min(n, avail // (_PER_CHUNK * per))))


class Operators:
    """H(t) (convolution of the padded latent with each exposure's kernel, valid part),
    D, and the adjoints H(t)^T and D^T, for a latent x of shape (1, C, X, Y).

    kernels: (n, C, k, k), one per exposure and channel.  The convolution is computed
    directly, as conv2d does it: im2col (``F.unfold``: every k x k latent patch as a
    column) times the matrix of all exposures' flipped kernels - the true convolution
    h * x, identical to conv2d (tests: experiments/test_imagemm.py).  The adjoint is the
    exact transpose: kernel matrix transposed times the residuals, then col2im
    (``F.fold``, which sums the overlapping patches).  One matrix product per channel
    covers every exposure; latent rows are processed in bands to bound memory."""

    def __init__(self, kernels: torch.Tensor, r: int = 1, chunk: int | None = None,
                 band_bytes: float = 512e6):
        self.n, self.C, self.ks, _ = kernels.shape
        self.r = r
        self.chunk = chunk or self.n
        # correlation weights of the true convolution: flipped kernels, (n, C, k*k)
        self.W = kernels.flip(-2, -1).reshape(self.n, self.C, self.ks * self.ks).contiguous()
        self.band_bytes = band_bytes

    def ranges(self):
        for a in range(0, self.n, self.chunk):
            yield a, min(a + self.chunk, self.n)

    def _band(self, width: int, m: int) -> int:
        """Output rows per band (a multiple of r): the im2col matrix (k^2 x rows*width) and
        the product (m x rows*width) must fit in ``band_bytes``."""
        per_row = 4 * width * (self.ks * self.ks + m)
        rows = max(self.r, int(self.band_bytes // per_row) // self.r * self.r)
        return rows

    def forward(self, x: torch.Tensor, a: int, b: int) -> torch.Tensor:
        """D H(t) x for exposures a..b-1 -> (b - a, C, d, d)."""
        m = b - a
        k = self.ks
        Hv, Wv = x.shape[-2] - k + 1, x.shape[-1] - k + 1          # valid output (r d x r d)
        out = torch.empty(m, self.C, Hv, Wv, device=x.device, dtype=x.dtype)
        band = self._band(Wv, m)
        for c in range(self.C):
            Wc = self.W[a:b, c]
            for r0 in range(0, Hv, band):
                r1 = min(r0 + band, Hv)
                cols = F.unfold(x[:, c:c + 1, r0:r1 + k - 1], k)[0]      # (k^2, rows * Wv)
                out[:, c, r0:r1] = (Wc @ cols).view(m, r1 - r0, Wv)
        return pool(out, self.r)

    def adjoint_sum(self, z: torch.Tensor, a: int, b: int) -> torch.Tensor:
        """sum_t H(t)^T D^T z(t) over exposures a..b-1; z (b - a, C, d, d) -> (1, C, X, Y)."""
        m = b - a
        k = self.ks
        zu = unpool(z, self.r)                                           # (m, C, r d, r d)
        Hv, Wv = zu.shape[-2:]
        X, Y = Hv + k - 1, Wv + k - 1
        out = torch.zeros(1, self.C, X, Y, device=z.device, dtype=z.dtype)
        band = self._band(Wv, m)
        for c in range(self.C):
            WcT = self.W[a:b, c].T                                       # (k^2, m)
            for r0 in range(0, Hv, band):
                r1 = min(r0 + band, Hv)
                cols = WcT @ zu[:, c, r0:r1].reshape(m, -1)              # (k^2, rows * Wv)
                out[0, c, r0:r1 + k - 1] += F.fold(cols[None], (r1 - r0 + k - 1, Y), k)[0, 0]
        return out


class BiggsAndrews:
    """Vector extrapolation of Biggs & Andrews (1997, Appl. Opt. 36, 1766), eqs. (11)-(15):
    the standard accelerator for multiplicative (Richardson-Lucy type) iterations.  Not
    part of ImageMM; optional.

        y_k = x_k + alpha_k h_k,          h_k = x_k - x_{k-1}
        x_{k+1} = psi(y_k)                (one ImageMM update from y_k)
        g_k = x_{k+1} - y_k
        alpha_k = sum(g_{k-1} g_{k-2}) / sum(g_{k-2} g_{k-2}),   0 <= alpha_k < 1

    The extrapolated point is kept strictly positive (the MM update needs x > 0).
    ``restart`` drops the history (the next step is a plain MM step), for mm_restore's
    adaptive restart when the objective increases (O'Donoghue & Candes 2015): without it the
    extrapolation keeps jittering noise-dominated pixels and a sky-dominated cutout never
    satisfies the stopping rule."""

    def __init__(self, floor: float):
        self.floor = floor
        self.x_prev = self.g1 = self.g2 = None
        self.alpha = 0.0
        self.restarts = 0

    def restart(self):
        self.x_prev = self.g1 = self.g2 = None
        self.restarts += 1

    def extrapolate(self, x: torch.Tensor) -> torch.Tensor:
        self.alpha = 0.0
        if self.g2 is not None and self.x_prev is not None:
            a = float((self.g1 * self.g2).sum() / (self.g2 * self.g2).sum().clamp_min(1e-30))
            self.alpha = min(max(a, 0.0), 0.999)
        if self.alpha == 0.0:
            return x
        return (x + self.alpha * (x - self.x_prev)).clamp_min(self.floor)

    def update(self, x: torch.Tensor, y: torch.Tensor, x_new: torch.Tensor):
        self.g2, self.g1 = self.g1, x_new - y
        self.x_prev = x


@torch.no_grad()
def mm_restore(y: torch.Tensor, var: torch.Tensor, mask: torch.Tensor, kernels: torch.Tensor,
               x0: torch.Tensor, r: int = 1, kappa: float = 2.0, robust: bool = True, delta: float = 2.0,
               max_iters: int = 1000, epsilon: float = 1e-6, mu: float = 0.1, chunk: int | None = None,
               accelerate: bool = False, stop: str = "c15", min_iters: int = 0, log=None,
               bg: torch.Tensor | None = None, stars: dict | None = None, smooth: float = 0.0,
               smooth_sigma: float = 1.0, pedestal=0.0,
               whyte: dict | None = None) -> tuple[torch.Tensor, dict]:
    """Algorithms 1-3 on one cutout.

    ``whyte`` (r = 1), optional: the update of Whyte, Sivic & Zisserman for images with saturated pixels
    ("Deblurring shaken and partially saturated images", IJCV 110:185, 2014, Algorithm 1), in this multi-
    frame form: {"level": (n, C) each exposure's saturation in its units, "saturated": (n, C, d, d) its pixels
    whose resampling uses a saturated raw sample (their recorded values in ``y``), "phi": 0.9, "a": 50,
    "erode": 3, "soft": 3}.  Every iteration the latent is split (their Eqs. 23-25, Sec. 5.5) into the pixels
    U at most phi x the saturation level, eroded by a disk of "erode" px, and the rest S; the mask of U
    blurred by a Gaussian of "soft" px.  U is updated from the valid measurements S cannot reach - outside S
    dilated by the kernels' non-zero footprint (their V) - each pixel by the share of its footprint V holds,
    1 for the rest (Eq. 18); S from all the data through the smooth saturation response
    R(x) = x - log(1 + exp(a (x/L - 1))) L / a, L the exposure's saturation (Eqs. 19-22): a measurement the
    model saturates no longer pulls.  A bright latent pixel behind saturation is estimated from incomplete
    data, and its errors, spread by the blur, rang round every saturated star - dark crescents, rings, a
    plateau - even with the saturated pixels discarded (their Secs. 3-4; M 42, 2026-10-07).


    ``pedestal`` (scalar or (1, C, 1, 1)): a constant added to the exposures and to the initial
    guess, and taken off the result.  The kernels must have unit sum (``unit_sum``; any excess e turns
    into a sky offset of -P e), so the model is unchanged - except
    that the non-negativity then applies to latent + pedestal.  The exposures are sky-subtracted,
    and deconvolution amplifies the sky noise (M 42, DWARF 3: ~35 ADU rms on the latent against
    ~1 on the coadd), so without it half the background pixels of the latent are clipped at 0
    (a biased, textured sky) and any slight excess of a kernel's wing over a star's is paid for
    by emptying the sky round the star to 0 instead of by a shallow dip.  The stopping rule
    measures the flux of the latent without the pedestal.

    ``bg`` (1, C, X, Y) >= 0, optional: a fixed smooth background on the latent grid.  The model is
    then y(t) ~ D H(t) (x + bg) and the multiplicative update applies to x alone, u = H^T(W y) /
    H^T(W H (x + bg)) - the majorization of the same objective for x >= 0 with a known non-negative
    background (Lanteri et al. 2001; the point-source + smooth-background split of MCS, Magain et
    al. 1998).  Returns x; the restoration is x + bg (``restore_cutout``).

    ``stars``, optional: point sources as explicit components (Magain, Courbin & Sohy 1998, ApJ 494,
    472, Eq. 5): {"stamps": (K, ss, ss) unit-sum g_sigma profiles at each star's sub-pixel position,
    "iy", "ix": (K,) latent index of each stamp's top-left corner, "a": (K, C) initial amplitudes}.
    The model is then y(t) = D H(t) (x + bg + sum_k a_k s_k): through Eq. 11 each star is the exposure's
    own PSF f(t) at its sub-pixel position, a point source correctly sampled at the restoration's
    resolution.  A pixel latent alone cannot hold one between pixel centres: it concentrates the star
    into a few pixels and empties the pixels round it to keep the model close to the data - the
    shrunken star and the dark ring of every positivity-constrained deconvolution (MCS Sec. 2).  The
    amplitudes get the same majorization as the pixels (a linear model with non-negative coefficients):
    a_k <- a_k <s_k, H^T(W y)> / <s_k, H^T(W H(model))>, from the two adjoint images the pixel update
    already computes.  Returned in info["star_a"]; the restoration adds sum_k a_k s_k.

    ``stars["halo"]`` (optional, (K, C, hh, hh) with "hy", "hx" the top-left exposure-window pixel): each
    bright star's own PSF residual per unit amplitude in the exposures (MCS: the PSF of the image is an
    analytic model plus a numerical part measured on its own stars), a fixed term of the model scaled by
    the star's amplitude.  The PSF light of a star that the kernels lack - on M 42 every bright star's halo
    sits 2 - 3 px off its core, more than the field model's and by a different amount for each - is then
    the star's, not restored into the image as a coloured arc beside it with an empty gap.

    ``smooth`` > 0 (with ``stars``): MCS's regularisation of the pixel channel, R(x) = 1/2 ||x - g * x||^2
    with g the Gaussian of the restoration's resolution (``smooth_sigma``, latent pixels; Magain et al.
    1998 Eq. 7): structure finer than the resolution costs the pixel channel, so a star's light goes to
    its point-source component - near a point source the split between the two channels is otherwise
    arbitrary (Cantale et al. 2016, Firedec).  Applied by Green's (1990) one-step-late rule,
    u = H^T(W y) / (H^T(W H model) + lambda dR/dx), lambda = ``smooth`` x the data term's curvature
    per pixel (the median of sum_t m / v over the latent).

    y, var, mask: (n, C, d, d) exposures y(t), variances v(t), masks m(t) in {0, 1};
    kernels: (n, C, ks, ks) PSFs on the latent grid (f(t), or h(t) of Eq. 11);
    x0: (1, C, X, Y), strictly positive, of ``latent_shape``.
    robust=True: Algorithm 3 with the Huber loss (delta); False: Algorithm 1 (r = 1) / 2.
    Stopping rule ``stop``: "c15" - Eq. C15, |mean over m~ of u'_k / u'_{k-1} - 1| < epsilon
    (the paper; a necessary condition for u'_k ~ u'_{k-1}: ratios above and below 1 can cancel
    in the mean); "elementwise" - mean over m~ of |u'_k / u'_{k-1} - 1| < epsilon (u'_k ~ u'_{k-1}
    pixel by pixel).  On M 27 (experiments/diag_convergence.py, inside the field) at
    epsilon = 1e-6 the first stops at 185 iterations (max 11 %, rms 0.5 % of the peak from
    the 1500-iteration solution, the maximum at the brightest star cores), the second at 784
    (max 3.5 %, rms 0.2 %).  Or after max_iters.
    Returns (x, info)."""
    n = y.shape[0]
    ped = torch.as_tensor(pedestal, device=x0.device, dtype=x0.dtype)
    if ped.ndim == 0:
        ped = ped.view(1, 1, 1, 1)
    if bool((ped > 0).any()):
        y = y + ped
        x0 = x0 + ped
    if chunk is None:
        chunk = auto_chunk(n, y.shape[1], y.shape[-1], y.device)
    ops = Operators(kernels, r, chunk)

    def W_(a, b):                       # W(t) = m(t) / v(t), per chunk (not stored for all exposures)
        return torch.where(mask[a:b] > 0, 1.0 / var[a:b].clamp_min(1e-30), torch.zeros_like(var[a:b]))
    # effective mask m~ of Eq. C15
    frac = torch.zeros_like(x0)
    for a, b in ops.ranges():
        frac += ops.adjoint_sum(mask[a:b], a, b)
    m_eff = (frac / n > mu).float()
    M_eff = float(m_eff.sum())
    num = None
    if not robust and whyte is None:   # Eq. 8: the numerator does not depend on x
        num = torch.zeros_like(x0)
        for a, b in ops.ranges():
            num += ops.adjoint_sum(W_(a, b) * y[a:b], a, b)
    acc = BiggsAndrews(float(x0.min())) if accelerate else None
    if accelerate and stop != "flux":
        # extrapolated steps bring the mean of u'_k / u'_{k-1} to 1 about 100x sooner relative
        # to the true convergence (measured against a 20000-iteration run, experiments/
        # diag_accel.py): at epsilon / 100 the accelerated result is closer to the fixed point
        # than the plain run stopped at epsilon
        epsilon = epsilon / 100
    x = x0.clone()
    if smooth > 0:
        curv = torch.zeros_like(x0)
        for a, b in ops.ranges():
            curv += ops.adjoint_sum(W_(a, b), a, b)
        lam = smooth * float(curv[curv > 0].median()) if (curv > 0).any() else 0.0
        gk = int(2 * np.ceil(3 * smooth_sigma) + 1)
        g1 = torch.exp(-((torch.arange(gk, device=x0.device, dtype=x0.dtype) - gk // 2) ** 2) / (2 * smooth_sigma ** 2))
        g1 = g1 / g1.sum()

        def G_(z):                                        # separable Gaussian blur, reflect padding
            p = gk // 2
            zz = F.pad(z, (p, p, p, p), mode="reflect")
            zz = F.conv2d(zz.reshape(-1, 1, *zz.shape[-2:]), g1.view(1, 1, 1, -1))
            zz = F.conv2d(zz, g1.view(1, 1, -1, 1))
            return zz.reshape(z.shape)
    if stars is not None:
        C_ = x0.shape[1]
        st_a = torch.as_tensor(stars["a"], device=x0.device, dtype=x0.dtype).clamp_min(1e-6).clone()  # (K, C)
        st_iy, st_ix = list(map(int, stars["iy"])), list(map(int, stars["ix"]))
        ss = int(stars["stamps"].shape[-1]); hs = ss // 2
        sig_ = float(stars.get("sigma", 1.0))
        # each star's sub-pixel position per channel, relative to its stamp's centre pixel (``point_sources``
        # fits them on the coadd: each colour of a star sits slightly elsewhere)
        off_ = np.asarray(stars["off"], np.float64)
        if off_.ndim == 2:
            off_ = np.repeat(off_[:, None, :], C_, 1)
        st_off = torch.as_tensor(off_, device=x0.device, dtype=torch.float64)                         # (K, C, 2)
        st_off0 = st_off.clone()
        e_ = torch.arange(-hs, hs + 2, device=x0.device, dtype=torch.float64) - 0.5

        def render(off):            # unit-sum g_sigma integrated over pixels, (K, C, ss, ss)
            gy = torch.diff(torch.erf((e_[None, None, :] - off[..., 0:1]) / (math.sqrt(2) * sig_)), dim=-1)
            gx = torch.diff(torch.erf((e_[None, None, :] - off[..., 1:2]) / (math.sqrt(2) * sig_)), dim=-1)
            st_ = gy[..., :, None] * gx[..., None, :]
            return (st_ / st_.sum((-2, -1), keepdim=True)).to(x0.dtype)
        st_stamps = render(st_off)

        if stars.get("halo") is not None:
            ha_ = torch.as_tensor(stars["halo"], device=x0.device, dtype=x0.dtype)            # (K, C, hh, hh)
            hy_, hx_ = list(map(int, stars["hy"])), list(map(int, stars["hx"]))
            hh_ = ha_.shape[-1]

            def halo_image(a_):      # sum_k a_k halo_k on the exposure window, (C, d, d)
                img = torch.zeros(y.shape[1:], device=x0.device, dtype=x0.dtype)
                d0, d1 = img.shape[-2:]
                for q in range(len(hy_)):
                    ya, xa = hy_[q], hx_[q]
                    y_lo, x_lo = max(ya, 0), max(xa, 0)
                    y_hi, x_hi = min(ya + hh_, d0), min(xa + hh_, d1)
                    if y_hi <= y_lo or x_hi <= x_lo:
                        continue
                    img[:, y_lo:y_hi, x_lo:x_hi] += a_[q][:, None, None] * ha_[q][:, y_lo - ya:y_hi - ya, x_lo - xa:x_hi - xa]
                return img

        def star_image(a_):
            img = torch.zeros_like(x0)
            for q in range(len(st_iy)):
                img[0, :, st_iy[q]:st_iy[q] + ss, st_ix[q]:st_ix[q] + ss] += a_[q][:, None, None] * st_stamps[q]
            return img

        def star_dot(z, stamps=None):  # <s_k, z> per star and channel -> (K, C)
            stamps = st_stamps if stamps is None else stamps
            return torch.stack([(z[0, :, st_iy[q]:st_iy[q] + ss, st_ix[q]:st_ix[q] + ss] * stamps[q]).sum((-2, -1))
                                for q in range(len(st_iy))])
    if whyte is not None and (r != 1 or not bool((whyte["saturated"] > 0).any())):
        whyte = None                   # (the update is for data with saturated pixels; without any it is the paper's)
    if whyte is not None:
        w_L = torch.as_tensor(np.asarray(whyte["level"], np.float32), device=x0.device).view(n, -1, 1, 1)
        w_sat = whyte["saturated"]
        w_phi, w_a = float(whyte.get("phi", 0.9)), float(whyte.get("a", 50.0))
        w_er = int(whyte.get("erode", 3))
        dd_ = torch.arange(-w_er, w_er + 1, device=x0.device, dtype=x0.dtype)
        w_disk = ((dd_[:, None] ** 2 + dd_[None, :] ** 2) <= w_er ** 2).to(x0.dtype)[None, None]
        if whyte.get("support"):            # the PSF's measured support (beyond it the kernels hold numerical residue)
            sr_ = int(np.ceil(float(whyte["support"])))
            dd2 = torch.arange(-sr_, sr_ + 1, device=x0.device, dtype=x0.dtype)
            w_foot = ((dd2[:, None] ** 2 + dd2[None, :] ** 2) <= sr_ ** 2).to(x0.dtype)[None, None]
        else:
            w_foot = (kernels.abs().amax((0, 1)) > 0).to(x0.dtype)[None, None]           # the kernels' non-zeros
        o_e = int(round(exposure_origin(kernels.shape[-1], 1)))
        ws_ = float(whyte.get("soft", 3.0))
        wk_ = int(2 * np.ceil(3 * ws_) + 1)
        wg1 = torch.exp(-((torch.arange(wk_, device=x0.device, dtype=x0.dtype) - wk_ // 2) ** 2) / (2 * ws_ ** 2))
        wg1 = wg1 / wg1.sum()
        w_Lmin = w_L.amin(0, keepdim=True)                                                 # (1, C, 1, 1)

        def w_blur(z):
            p_ = wk_ // 2
            zz = F.pad(z, (p_, p_, p_, p_), mode="replicate")
            return F.conv2d(F.conv2d(zz, wg1.view(1, 1, 1, -1)), wg1.view(1, 1, -1, 1))

        def w_R(fx, L):                                     # smooth min(fx, L) and its derivative (Eqs. 21-22)
            t = (w_a * (fx / L - 1.0)).clamp(-60, 60)
            return fx - torch.log1p(torch.exp(t)) * L / w_a, 1.0 / (1.0 + torch.exp(t))
    u_prev, hist, converged, k = None, [], False, 0
    loss_prev, losses = float("inf"), []
    for k in range(1, max_iters + 1):
        xe = acc.extrapolate(x) if acc is not None else x
        xm = xe if bg is None else xe + bg                  # the model's sky: restored part + background
        if stars is not None:
            xm = xm + star_image(st_a)
        if robust or whyte is not None:
            num = torch.zeros_like(x0)
        den = torch.zeros_like(x0)
        split = None
        if whyte is not None:
            # U: latent pixels at most phi x the saturation (any channel above it: S), eroded (Eqs. 23, 29)
            Sb = ((xe - ped) > w_phi * w_Lmin).any(1, keepdim=True).to(x0.dtype)
            if bool(Sb.any()):
                Sb = (F.conv2d(Sb, w_disk, padding=w_er) > 0).to(x0.dtype)
                u_soft = (1.0 - w_blur(Sb)).clamp(0, 1)
                kh = w_foot.shape[-1] // 2
                reach = (F.conv2d(Sb, w_foot, padding=kh) > 0).to(x0.dtype)
                V_exp = (1.0 - reach)[0, :, o_e:o_e + y.shape[-2], o_e:o_e + y.shape[-1]]   # (1, d, d): their V
                num_S, den_S = torch.zeros_like(x0), torch.zeros_like(x0)
                fV, fA = torch.zeros_like(x0), torch.zeros_like(x0)
                split = True
        loss = 0.0                     # float64 accumulation of float32 chunk sums (MPS has no float64)
        if stars is not None and stars.get("halo") is not None:
            E_ = halo_image(st_a)
        for a, b in ops.ranges():
            fx = ops.forward(xm, a, b)
            if stars is not None and stars.get("halo") is not None:
                fx = fx + E_[None]
            Wk = W_(a, b)
            z = (y[a:b] - fx) / var[a:b].clamp_min(1e-30).sqrt()
            za = z.abs()
            # the objective at xe (Eq. 5 / Eq. 14): sum over valid pixels of rho(z)
            rho = torch.where(za <= delta, 0.5 * z * z, delta * (za - 0.5 * delta)) if robust else 0.5 * z * z
            loss += float((rho * (mask[a:b] > 0)).sum())
            if robust:                 # Eq. 17: W_rho = m / v * psi(r),  r = (y - D H x) / sigma  (Eq. 13)
                Wk = Wk * huber_psi(z, delta)
            if split is not None:
                # S (Eq. 20): every measurement, the saturated ones included, through R
                Rf, dR = w_R(fx, w_L[a:b])
                allm = ((mask[a:b] > 0) | (w_sat[a:b] > 0)).to(fx.dtype)
                WS = allm / var[a:b].clamp_min(1e-30) * dR
                if robust:
                    zS = (y[a:b] - Rf) / var[a:b].clamp_min(1e-30).sqrt()
                    WS = WS * huber_psi(zS, delta)
                num_S += ops.adjoint_sum(WS * y[a:b], a, b)
                den_S += ops.adjoint_sum(WS * Rf, a, b)
                del Rf, dR, allm, WS
                # U (Eq. 18): the valid measurements outside S's reach, and the share of each footprint they hold
                fA += ops.adjoint_sum(Wk, a, b)
                Wk = Wk * V_exp[None]
                fV += ops.adjoint_sum(Wk, a, b)
            if robust or whyte is not None:
                num += ops.adjoint_sum(Wk * y[a:b], a, b)
            den += ops.adjoint_sum(Wk * fx, a, b)
            del fx, Wk, z, za, rho
        losses.append(loss)
        # (a rise above float32 summation noise, ~1e-7 relative)
        if acc is not None and loss > loss_prev * (1 + 1e-6) and acc.alpha > 0:
            # the extrapolated point made the objective worse: take a plain MM step from x instead
            # (MM never increases it) and start the extrapolation history afresh
            acc.restart()
            loss_prev = float("inf")
            continue
        loss_prev = loss
        if smooth > 0:                                     # one-step-late MCS smoothing of the pixel channel
            d_ = xe - G_(xe)
            den = (den + lam * (d_ - G_(d_))).clamp_min(1e-3 * den.clamp_min(0) + 1e-30)
        u = torch.where(den > 0, num / den.clamp_min(1e-30), torch.ones_like(den))      # Eq. 8 / 16
        u = u.clamp(1.0 / kappa, kappa)                                                 # Eq. 9
        if split is not None:
            # Eq. 18: A^T(v g / A f) + 1 - A^T v - the ratio over V weighted by the share of each pixel's
            # (weighted) footprint V holds, 1 for the rest; Eq. 20 for S; combined through the blurred mask of U
            share = torch.where(fA > 0, fV / fA.clamp_min(1e-30), torch.zeros_like(fA)).clamp(0, 1)
            uS = torch.where(den_S > 0, num_S / den_S.clamp_min(1e-30), torch.ones_like(den_S)).clamp(1.0 / kappa, kappa)
            u = u_soft * (share * u + (1.0 - share)) + (1.0 - u_soft) * uS
            # the stopping rule over the pixels the data update (held pixels' u is 1 by construction and would
            # make the mean look converged: 37 iterations instead of ~110 on a synthetic field, far rms doubled)
            m_crit = m_eff * ((u_soft * share) > 0.5).to(m_eff.dtype)
            del num_S, den_S, fV, fA
        else:
            m_crit = m_eff
        if stars is not None:
            ua = star_dot(num) / star_dot(den).clamp_min(1e-30)
            a_prev = st_a
            st_a = st_a * ua.clamp(1.0 / kappa, kappa)
        x_new = xe * u                                                                  # Eq. 7
        if acc is not None:
            acc.update(x, xe, x_new)
        if stop == "flux":
            # flux-weighted relative change of the image, sum |x_k - x_{k-1}| / sum x_k over m~ (with point
            # sources: of the pixel channel and the stars together - stopping on the pixels alone left the
            # star amplitudes short, data - model +10 to +25 sigma over every star core)
            dx = float((m_crit * (x_new - x).abs()).sum())
            tot = float((m_crit * (x_new - ped)).abs().sum())
            if stars is not None:
                dx += float((st_a - a_prev).abs().sum())
                tot += float(st_a.sum())
            crit = dx / max(tot, 1e-30)
        elif u_prev is not None:
            xi = u / u_prev
            M_c = max(float(m_crit.sum()), 1.0)
            if stop == "c15":
                crit = abs(float((m_crit * xi).sum()) / M_c - 1.0)                       # Eq. C15
            else:
                crit = float((m_crit * (xi - 1).abs()).sum()) / M_c
        else:
            crit = None
        x = x_new
        if crit is not None:
            hist.append(crit)
            if log:
                log(k, crit)
            if crit < epsilon and k >= min_iters:
                converged = True
                break
        u_prev = u
    if stars is not None:
        x = x + star_image(st_a)                            # the restoration includes its point sources
    x = x - ped
    return x, {"iterations": k, "converged": converged, "criterion": hist, "loss": losses,
               "star_a": None if stars is None else st_a.cpu().numpy(),
               "star_off": None if stars is None else (st_off - st_off0).cpu().numpy(),
               "restarts": acc.restarts if acc is not None else 0, "effective_mask": m_eff,
               "coverage": frac / n, "chunk": chunk}


def initial_guess(y: torch.Tensor, mask: torch.Tensor, ks: int, r: int = 1, how: str = "median",
                  floor: float | None = None) -> torch.Tensor:
    """x0 (Sec. 4.1): the median (or mean) of the exposures over their valid pixels, sampled
    at every latent pixel's position on the exposure grid (latent l <-> exposure
    (l - exposure_origin) / r; bilinear, edge values continued into the padding), with
    non-positive pixels replaced by ``floor`` (default 1e-3 x the robust noise level of
    the median image)."""
    # per-pixel statistic over the exposures, in row bands (a masked copy of all exposures at
    # once would double the memory of the cutout)
    n, C, h_, w_ = y.shape
    band = max(1, int(2 ** 26 // max(n * C * w_, 1)))
    med = torch.empty((1, C, h_, w_), device=y.device, dtype=y.dtype)
    for r0 in range(0, h_, band):
        yy = torch.where(mask[:, :, r0:r0 + band] > 0, y[:, :, r0:r0 + band], torch.full_like(y[:, :, r0:r0 + band], float("nan")))
        med[:, :, r0:r0 + band] = (torch.nanmedian(yy, dim=0, keepdim=True).values if how == "median"
                                   else torch.nanmean(yy, 0, keepdim=True))
    del yy
    med = torch.nan_to_num(med, nan=0.0)
    if floor is None:
        dev = 1.4826 * (med - med.median()).abs().median()
        floor = max(1e-3 * float(dev), 1e-12)
    h, w = med.shape[-2:]
    X, Y = latent_shape(h, w, ks, r)
    o = exposure_origin(ks, r)
    ey = (torch.arange(X, device=y.device, dtype=torch.float32) - o) / r
    ex = (torch.arange(Y, device=y.device, dtype=torch.float32) - o) / r
    # grid_sample, align_corners=True: -1 / +1 are the centres of the first / last pixel
    gy = (ey / max(h - 1, 1) * 2 - 1)[:, None].expand(X, Y)
    gx = (ex / max(w - 1, 1) * 2 - 1)[None, :].expand(X, Y)
    grid = torch.stack([gx, gy], -1)[None]
    x0 = F.grid_sample(med, grid, mode="bilinear", padding_mode="border", align_corners=True)
    return torch.where(x0 > 0, x0, torch.full_like(x0, floor))


# ----------------------------------------------------------------- seeing groups
def seeing_groups(kernels: np.ndarray, n_groups: int) -> list[np.ndarray]:
    """Split exposures into ``n_groups`` equal-count groups by PSF width (half-light
    diameter of the channel-averaged PSF), sharpest first."""
    fw = np.array([_fwhm(k.mean(0)) for k in kernels])
    order = np.argsort(fw, kind="stable")
    return [g for g in np.array_split(order, n_groups) if len(g)]


def coadd_groups(Y, V, Mk, K, groups):
    """Reduce every group of exposures to one exposure of the same model:

        y_g = sum_t w_t y_t / sum_t w_t,   v_g = 1 / sum_t w_t,   m_g = [sum_t w_t > 0],   w_t = m_t / v_t

    y_g = sum_t (w_t / sum w) (f_t * x) + noise, i.e. the PSF of the coadd is the weight-
    averaged member PSF; with the member weights' ratios uniform over the cutout that is
    f_g = sum_t W_t f_t / sum_t W_t with W_t the cutout-mean weight (per channel), exact
    when the members share one PSF.  The Huber weights of Algorithm 3 then act on the
    group residuals, so an outlier in one exposure is diluted by the group size."""
    n, C, h, w = Y.shape
    Yg, Vg, Mg, Kg = [], [], [], []
    for g in groups:
        wt = np.where(Mk[g] > 0, 1 / np.maximum(V[g], 1e-30), 0)
        sw = wt.sum(0)
        Yg.append(np.where(sw > 0, (wt * Y[g]).sum(0) / np.maximum(sw, 1e-30), 0))
        Vg.append(np.where(sw > 0, 1 / np.maximum(sw, 1e-30), 1.0))
        Mg.append((sw > 0).astype(np.float32))
        Wm = wt.mean((2, 3))                                  # (members, C)
        Kg.append((K[g] * Wm[:, :, None, None]).sum(0) / np.maximum(Wm.sum(0), 1e-30)[:, None, None])
    return (np.stack(Yg).astype(np.float32), np.stack(Vg).astype(np.float32), np.stack(Mg).astype(np.float32),
            np.stack(Kg).astype(np.float32))


# ----------------------------------------------------------------- one cutout of a session
def restore_cutout(es, y0: int, y1: int, x0: int, x1: int, idx: list[int] | None = None, r: int = 1,
                   kernels: np.ndarray | None = None, robust: bool = True, psf_model: str = "empirical",
                   n_groups: int = 0, device=None, background: bool = False, saturated: str = "whyte",
                   init: str = "exposures", **kw):
    """ImageMM (Algorithm 3 by default) of the prepared exposures ``es``
    (exposures.ExposureSet) on the reference-grid window [y0, y1) x [x0, x1).

    ``init``: "exposures" (default) - x0 the median of the exposures, every recorded value (Sec. 4.1: "the
    mean or median of the input exposures", non-positive pixels replaced); "valid" - the median over the
    valid measurements only.  A saturated star's core is masked in every exposure: started from the valid
    ones it began at the floor - a black disc ringed by its own light on M 42 (2026-10-07).

    ``saturated``: "whyte" (default) - Whyte, Sivic & Zisserman's update for saturated images
    (``mm_restore``'s ``whyte``) where the window has saturated pixels; "mask" - the paper's binary masks
    alone, under which every saturated star of M 42 had a dark crescent above it (its errors in the
    bright, saturated latent pixels spread by the blur).

    ``background``: restore on a pedestal (``mm_restore``: 50 x the exposures' median pixel noise
    per channel, added to the data and taken off the result), so that the latent's sky keeps its
    noise instead of being clipped at 0.

    ``kernels``: latent-grid kernels for super-resolution (Eq. 11), aligned with ``idx``;
    default: the exposures' PSFs f(t) (``psf_model`` "empirical" or "moffat").
    ``n_groups`` > 0: seeing groups (``coadd_groups``) instead of every exposure.
    Returns (latent image cropped to the window on the latent grid, info)."""
    device = device or pick_device()
    idx = es.usable() if idx is None else idx
    import inspect
    use_w = (saturated == "whyte" and r == 1 and not n_groups and hasattr(es, "sat")
             and "censored" in inspect.signature(es.windows).parameters)
    if use_w:          # the pixels whose resampling used a saturated raw sample, with their recorded values
        Y, V, Mk, Cs = es.windows(idx, y0, y1, x0, x1, censored=True)
    else:
        Y, V, Mk = es.windows(idx, y0, y1, x0, x1)
        Cs = None
    at = ((y0 + y1 - 1) / 2, (x0 + x1 - 1) / 2)                # the PSFs where the cutout is
    # unit sum whatever the source: the sky pedestal below assumes it (``unit_sum``)
    k = unit_sum(es.kernels(idx, psf_model, at=at) if kernels is None else kernels)
    if n_groups:
        groups = seeing_groups(es.kernels(idx, psf_model, at=at), n_groups)
        Y, V, Mk, k = coadd_groups(Y, V, Mk, k, groups)
    yt, vt, mt = (torch.from_numpy(z).to(device) for z in (Y, V, Mk))
    kt = torch.from_numpy(k).to(device)
    ks = k.shape[-1]
    x0_ = initial_guess(yt, torch.ones_like(mt) if init == "exposures" else mt, ks, r)
    whyte = None
    if Cs is not None and Cs.any():
        T = np.stack([np.asarray(es.params[k_]["T"], np.float64) for k_ in idx])          # (n, C)
        support = [float(es.psf_ref[c].get("support") or 0) for c in range(3) if es.psf_ref and es.psf_ref[c] is not None]
        whyte = {"level": (float(es.sat) / T).astype(np.float32),     # each exposure's saturation in its units
                 "saturated": torch.from_numpy(Cs).to(device), "phi": 0.9, "a": 50.0, "erode": 3, "soft": 3.0,
                 "support": max(support) if support and max(support) > 0 else None}
    del Cs
    # output sample j sits at exposure coordinate j / r: latent index exposure_origin + j (an
    # integer for r = 1 with odd, and r = 2 with even, kernels)
    o = exposure_origin(ks, r)
    assert abs(o - round(o)) < 1e-9
    o = int(round(o))
    ped = 0.0
    if background:
        sd = vt.clamp_min(0).sqrt()
        ped = torch.stack([50.0 * sd[:, c][mt[:, c] > 0].median() if bool((mt[:, c] > 0).any()) else sd.new_tensor(0.0)
                           for c in range(vt.shape[1])]).view(1, -1, 1, 1)
    x, info = mm_restore(yt, vt, mt, kt, x0_, r=r, robust=robust, pedestal=ped, whyte=whyte, **kw)
    info["saturated_pixels"] = 0 if whyte is None else int((whyte["saturated"].amax(0) > 0).sum())
    if background:
        info["pedestal"] = [float(v) for v in ped.flatten()]
    h, w = (y1 - y0) * r, (x1 - x0) * r
    out = x[0, :, o:o + h, o:o + w].permute(1, 2, 0).cpu().numpy()
    info["n_exposures"] = len(idx)
    info["psf_size"] = ks
    for key in ("effective_mask", "coverage"):
        info[key] = info[key][0, :, o:o + h, o:o + w].permute(1, 2, 0).cpu().numpy()
    return out, info


# ----------------------------------------------------------------- forward model on a stack grid
def lanczos_half_shift(z: torch.Tensor, a: int = 4) -> torch.Tensor:
    """Resample (..., H, W) at +1/2 pixel in both axes with a Lanczos-a kernel (2a taps,
    normalised): sample j of the output is z at j + 1/2.  Exact for band-limited signals up
    to the Lanczos window; the output loses a - 1/2 ... a pixels at the high edges (valid
    part only): (H - 2a + 1, W - 2a + 1), sample j at input coordinate j + a - 1/2."""
    t = torch.arange(-a + 1, a + 1, dtype=torch.float64) - 0.5            # tap offsets from the new sample
    wts = torch.sinc(t) * torch.sinc(t / a)
    wts = (wts / wts.sum()).to(z.dtype).to(z.device)
    zz = z.reshape(-1, 1, *z.shape[-2:])
    zz = F.conv2d(zz, wts.view(1, 1, 1, -1))
    zz = F.conv2d(zz, wts.view(1, 1, -1, 1))
    return zz.reshape(*z.shape[:-2], *zz.shape[-2:])


def stack_forward(x: torch.Tensor, kernels: torch.Tensor, s: int) -> tuple[torch.Tensor, float]:
    """Predicted exposure-grid images D H x for a patch x (B, C, P, P) of a stack grid at
    integer scale s whose pixel u is centred on reference coordinate (u + 1/2)/s - 1/2 (the
    drizzle convention of stacking.py) and whose origin is a multiple of s.

    kernels (G, C, k, k) on the stack grid (latent grid of ImageMM with r = s; for s = 1
    the exposure PSFs).  Returns (prediction (B, G, C, n, n), exposure-grid coordinate of
    prediction pixel 0 relative to the patch origin / s).

    s = 1: valid convolution; output j is exposure pixel j + (k-1)/2.
    s > 1 (k even, from Eq. 11): valid convolution, then - because ImageMM's latent pixels
    are co-sited with exposure pixel centres while drizzle pixels sit half a pixel off - a
    Lanczos-4 resampling by half a stack pixel (the PSF-blurred prediction is band-limited),
    then D (s x s average pooling)."""
    B, C, P, _ = x.shape
    G, _, k, _ = kernels.shape
    w = kernels.flip(-2, -1).reshape(G * C, 1, k, k)
    out = F.conv2d(x.repeat(1, G, 1, 1), w, groups=G * C)                   # (B, G*C, P-k+1, ...)
    if s == 1:
        return out.view(B, G, C, *out.shape[-2:]), (k - 1) / 2
    # valid output j is the kernel window centred at stack coordinate j + (k-1)/2 (a half-integer
    # for even k); after the half shift, sample j sits at stack coordinate c0 + j:
    out = lanczos_half_shift(out)
    c0 = (k - 1) / 2 + 4 - 0.5
    # exposure pixel i is centred at stack coordinate s i + (s-1)/2, i.e. it is the mean of the
    # s x s samples at stack coordinates s i ... s i + s - 1: pool blocks starting at a sample
    # whose stack coordinate is a multiple of s
    start = int(round((-c0) % s))
    out = out[..., start:, start:]
    n = min(out.shape[-2], out.shape[-1]) // s
    out = pool(out[..., :n * s, :n * s], s)
    e0 = (c0 + start) / s                          # exposure coordinate of pooled pixel 0
    return out.view(B, G, C, n, n), e0


# ----------------------------------------------------------------- saturated stars
def local_psf_correction(es, window: tuple[int, int, int, int], margin: int = 128, R: int = 16,
                         min_stars: int = 3) -> np.ndarray | None:
    """Radial correction C(r) (3, R + 1) of the field PSF model for a cutout, from the cutout's own stars
    in the coadd (Magain et al. 1998 and Cantale et al. 2016 build the PSF from the stars of the image
    being deconvolved).  The field model is a polynomial over PSF stars from the whole frame; where few
    of them are (M 42's cluster, on the brightest nebula) its wing came out 10 - 40 % too strong at
    2 - 14 px against the stars actually there, and ImageMM, whose model then already exceeded the data
    round every bright star, emptied the latent there: the dark disc round every star.

    Each bright unsaturated star within ``margin`` of the window: coadd stamp = a K + plane (the nebula
    gradient), K the field model at the star; the ratio of its ring means (plane removed, / a) to K's,
    per channel; C = the flux-weighted median over the stars, 1 within 1 px (the core sets a), smoothed
    over 3 rings and limited to 0.3 - 2.  None with fewer than ``min_stars`` stars."""
    from .exposures import interp_nodes
    y0, y1, x0, x1 = window
    cat = es.cat
    ref = (es.ref - es.sky_ref).astype(np.float32)
    H, W = ref.shape[:2]
    xs, ys = np.asarray(cat["x"], float), np.asarray(cat["y"], float)
    sel = (xs > x0 - margin) & (xs < x1 + margin) & (ys > y0 - margin) & (ys < y1 + margin)
    sel &= (xs > R + 1) & (xs < W - R - 2) & (ys > R + 1) & (ys < H - R - 2)
    peak = np.asarray(cat["peak"], float)
    sel &= peak < 0.5 * float(es.sat)
    if sel.sum() == 0:
        return None
    sel &= peak >= np.percentile(peak[sel], 50)             # the brighter half: their wings rise out of the noise
    yy, xx = np.mgrid[-R:R + 1, -R:R + 1]
    ri = np.minimum(np.round(np.hypot(yy, xx)).astype(int), R)
    cnt = np.bincount(ri.ravel(), minlength=R + 1)
    ratios, wts = [[], [], []], []
    for x, y in zip(xs[sel], ys[sel]):
        iy, ix = int(round(y)), int(round(x))
        st = ref[iy - R:iy + R + 1, ix - R:ix + R + 1]
        w_ = None
        for c in range(3):
            K = interp_nodes(np.asarray(es.psf_ref[c]["nodes"]), es.nodes, y, x)
            h = K.shape[-1] // 2
            if h < R:
                K = np.pad(K, R - h); h = R
            K = K[h - R:h + R + 1, h - R:h + R + 1]
            sh = np.float32([[1, 0, x - ix], [0, 1, y - iy]])
            K = cv2.warpAffine(K.astype(np.float32), sh, K.shape[::-1], flags=cv2.INTER_CUBIC)
            A = np.stack([K.ravel(), np.ones(K.size), yy.ravel(), xx.ravel()], 1)
            coef, *_ = np.linalg.lstsq(A, st[..., c].ravel(), rcond=None)
            if coef[0] <= 0:
                break
            d = (st[..., c] - (coef[1] + coef[2] * yy + coef[3] * xx)) / coef[0]
            pd = np.bincount(ri.ravel(), d.ravel(), minlength=R + 1) / cnt
            pk = np.bincount(ri.ravel(), K.ravel(), minlength=R + 1) / cnt
            ratios[c].append(pd / np.maximum(pk, 1e-12))
            w_ = coef[0] if w_ is None else w_ + coef[0]
        else:
            wts.append(w_)
            continue
        for c in range(3):                                   # a channel failed: drop the star in all
            if len(ratios[c]) > len(wts):
                ratios[c].pop()
    if len(wts) < min_stars:
        return None
    wts = np.asarray(wts)
    C = np.ones((3, R + 1))
    for c in range(3):
        Rm = np.asarray(ratios[c])
        order = np.argsort(Rm, 0)                        # flux-weighted median per ring
        cw = np.cumsum(wts[order], 0)
        j = np.argmax(cw >= 0.5 * wts.sum(), 0)
        cols = np.arange(Rm.shape[1])
        med = Rm[order[j, cols], cols]
        med[:2] = 1.0
        C[c] = np.clip(np.convolve(np.r_[med[0], med, med[-1]], np.ones(3) / 3, "valid"), 0.3, 2.0)
        C[c, :2] = 1.0
    return C


def local_psf_residual(es, window: tuple[int, int, int, int], margin: int = 256, R: int = 16,
                       min_stars: int = 3) -> np.ndarray | None:
    """The numerical part of the PSF at a cutout (Magain et al. 1998: the PSF is an analytic profile plus a
    numerical residual from the stars of the image itself): per channel, the flux-weighted median over
    the bright unsaturated stars within ``margin`` of the window of (coadd stamp - plane) / amplitude - K,
    K the field model at each star (sub-pixel centred), fitted as stamp = a K + plane.  Returns
    (3, 2R + 1, 2R + 1) to add to the kernels at their centre (``apply_psf_residual``), or None."""
    from .exposures import interp_nodes
    y0, y1, x0, x1 = window
    cat = es.cat
    ref = (es.ref - es.sky_ref).astype(np.float32)
    H, W = ref.shape[:2]
    xs, ys = np.asarray(cat["x"], float), np.asarray(cat["y"], float)
    peak = np.asarray(cat["peak"], float)
    sel = (xs > x0 - margin) & (xs < x1 + margin) & (ys > y0 - margin) & (ys < y1 + margin)
    sel &= (xs > R + 1) & (xs < W - R - 2) & (ys > R + 1) & (ys < H - R - 2) & (peak < 0.5 * float(es.sat))
    if sel.sum() < min_stars:
        return None
    sel &= peak >= np.percentile(peak[sel], 50)
    yy, xx = np.mgrid[-R:R + 1, -R:R + 1]
    res, wts = [], []
    cyw, cxw = (y0 + y1) / 2, (x0 + x1) / 2
    # the halo's asymmetry changes over the field (M 42, DWARF 3: displaced 2 - 3 px from the core, more in
    # blue and to the lower right): nearer stars count more (Gaussian of the window's size)
    scale = max(y1 - y0, x1 - x0)
    for x, y in zip(xs[sel], ys[sel]):
        iy, ix = int(round(y)), int(round(x))
        st = ref[iy - R:iy + R + 1, ix - R:ix + R + 1]
        one, w_ = [], 0.0
        for c in range(3):
            K = interp_nodes(np.asarray(es.psf_ref[c]["nodes"]), es.nodes, y, x)
            h = K.shape[-1] // 2
            if h < R:
                K = np.pad(K, R - h); h = R
            K = K[h - R:h + R + 1, h - R:h + R + 1]
            # the model at the star's sub-pixel position; the residual is taken in the kernel's frame
            sh = np.float32([[1, 0, x - ix], [0, 1, y - iy]])
            Ks = cv2.warpAffine(K.astype(np.float32), sh, K.shape[::-1], flags=cv2.INTER_CUBIC)
            A = np.stack([Ks.ravel(), np.ones(Ks.size), yy.ravel(), xx.ravel()], 1)
            coef, *_ = np.linalg.lstsq(A, st[..., c].ravel(), rcond=None)
            if coef[0] <= 0:
                break
            d = (st[..., c] - (coef[1] + coef[2] * yy + coef[3] * xx)) / coef[0] - Ks
            back = np.float32([[1, 0, -(x - ix)], [0, 1, -(y - iy)]])
            one.append(cv2.warpAffine(d.astype(np.float32), back, d.shape[::-1], flags=cv2.INTER_CUBIC))
            w_ += coef[0]
        else:
            res.append(one); wts.append(w_ * np.exp(-((y - cyw) ** 2 + (x - cxw) ** 2) / (2 * scale ** 2)))
    if len(wts) < min_stars:
        return None
    res, wts = np.asarray(res), np.asarray(wts)                 # (S, 3, n, n)
    order = np.argsort(res, 0)
    cw = np.cumsum(wts[order], 0)
    j = np.argmax(cw >= 0.5 * wts.sum(), 0)
    return np.take_along_axis(res, np.take_along_axis(order, j[None], 0), 0)[0]


def apply_psf_residual(kernels: np.ndarray, D: np.ndarray) -> np.ndarray:
    """Kernels (n, 3, k, k) plus the numerical residual D (3, m, m) at their centre; clipped at 0, unit sum."""
    out = kernels.copy()
    k = kernels.shape[-1]; m = D.shape[-1]
    if m > k:
        o = (m - k) // 2; D = D[:, o:o + k, o:o + k]; m = k
    o = (k - m) // 2
    out[:, :, o:o + m, o:o + m] += D[None].astype(out.dtype)
    out = np.clip(out, 0, None)
    return out / np.maximum(out.sum((-2, -1), keepdims=True), 1e-30)


def apply_psf_correction(kernels: np.ndarray, C: np.ndarray) -> np.ndarray:
    """Kernels (n, 3, k, k) times the radial correction C (3, R + 1) (1 beyond R), unit sum again."""
    n_, nc, k, _ = kernels.shape
    R = C.shape[-1] - 1
    rr = np.hypot(*np.mgrid[:k, :k] - k // 2)
    out = np.empty_like(kernels)
    for c in range(nc):
        m = np.interp(rr, np.arange(R + 1), C[c], right=C[c, -1] if C[c, -1] < 1 else 1.0)
        kc = kernels[:, c] * m
        out[:, c] = kc / np.maximum(kc.sum((-2, -1), keepdims=True), 1e-30)
    return out


def point_sources(es, r: int, sigma: float, window: tuple[int, int, int, int], origin: float, shape: tuple[int, int],
                  min_flux: float = 0.0, halo: bool = True) -> dict | None:
    """The stars of a cutout as point-source components for ``mm_restore`` (Magain, Courbin & Sohy 1998):
    each a unit-sum g_sigma (the restoration's own resolution, latent pixels) integrated over the
    latent pixels at the star's sub-pixel position, with its initial amplitude per channel from the
    coadd (aperture of 2 FWHM less the local level).  The stars: the catalogue's (WINPOS centroids),
    and the saturated ones from the full detection list (their cores are masked in the exposures; the
    amplitude comes from the unsaturated wings).  ``window``: (y0, y1, x0, x1) on the reference grid;
    latent index = r (reference - window origin) + ``origin``."""
    from scipy.special import erf
    y0, y1, x0, x1 = window
    cat = es.cat
    xs, ys = list(np.asarray(cat["x"], float)), list(np.asarray(cat["y"], float))
    if "all_x" in cat and len(cat["all_x"]):
        ax, ay = np.asarray(cat["all_x"], float), np.asarray(cat["all_y"], float)
        ix, iy = np.clip(np.round(ax).astype(int), 0, es.ref.shape[1] - 1), np.clip(np.round(ay).astype(int), 0, es.ref.shape[0] - 1)
        sat = es.ref[iy, ix].max(-1) >= 0.5 * float(es.sat)
        known = np.c_[ys, xs] if xs else np.zeros((0, 2))
        for x, y in zip(ax[sat], ay[sat]):
            if not len(known) or np.hypot(*(known - [y, x]).T).min() > 2:
                xs.append(x); ys.append(y)
    xs, ys = np.array(xs), np.array(ys)
    pad = 2
    inside = (xs >= x0 - pad) & (xs < x1 + pad) & (ys >= y0 - pad) & (ys < y1 + pad)
    xs, ys = xs[inside], ys[inside]
    if not len(xs):
        return None
    fw = float(getattr(es, "fwhm_ref", 4.0))
    ref = (es.ref - es.sky_ref).astype(np.float32)
    h = int(np.ceil(4 * sigma)) + 1
    ss = 2 * h + 1
    stamps, iys, ixs, amps, offs, halos = [], [], [], [], [], []
    HR = 16
    yyH, xxH = np.mgrid[-HR:HR + 1, -HR:HR + 1]
    rrH = np.hypot(yyH, xxH)
    taper = np.clip((HR - rrH) / 3, 0, 1) * np.clip((rrH - 1.5) / 1.0, 0, 1)

    def star_halo(x, y):
        """A bright star's own PSF residual on the coadd, per unit amplitude: (stamp - plane) / a - K,
        between 2 and 16 px (tapered), kept where it is significant; K the field PSF at the star."""
        iy, ix = int(round(y)), int(round(x))
        if iy < HR + 1 or ix < HR + 1 or iy > ref.shape[0] - HR - 2 or ix > ref.shape[1] - HR - 2:
            return None
        if ref[iy, ix].max() >= 0.5 * float(es.sat):
            return None
        out = np.zeros((3, 2 * HR + 1, 2 * HR + 1), np.float32)
        for c in range(3):
            K = interp_nodes(np.asarray(es.psf_ref[c]["nodes"]), es.nodes, y, x)
            h = K.shape[-1] // 2
            if h < HR:
                K = np.pad(K, HR - h); h = HR
            K = cv2.warpAffine(K[h - HR:h + HR + 1, h - HR:h + HR + 1].astype(np.float32),
                               np.float32([[1, 0, x - ix], [0, 1, y - iy]]), (2 * HR + 1, 2 * HR + 1), flags=cv2.INTER_CUBIC)
            st_ = ref[iy - HR:iy + HR + 1, ix - HR:ix + HR + 1, c]
            A = np.stack([K.ravel(), np.ones(K.size), yyH.ravel(), xxH.ravel()], 1)
            coef, *_ = np.linalg.lstsq(A, st_.ravel(), rcond=None)
            if coef[0] <= 0:
                return None
            d = st_ - (coef[1] + coef[2] * yyH + coef[3] * xxH) - coef[0] * K
            noise = 1.4826 * np.median(np.abs(d[rrH > HR - 2]))
            d = cv2.GaussianBlur(d, (0, 0), 1.0)
            out[c] = np.where(np.abs(d) > 2 * noise / 2.5, d, 0) * taper / coef[0]
        return out

    ra = 2 * fw
    from .exposures import interp_nodes
    yyR, xxR = np.mgrid[-6:7, -6:7]

    def fit_pos(x, y):
        """Per-channel sub-pixel position of a star on the coadd (MCS: positions are free parameters):
        stamp = a K(. - d) + plane, K the field PSF, d by Gauss-Newton.  Each colour of a star sits
        slightly elsewhere - atmospheric dispersion and lateral colour; on M 42 red above and blue below
        the luminance position by 0.05 - 0.1 px - and one position for all three left a coloured cap on
        one side of every bright star.  Saturated stars (no core) keep the catalogue position."""
        iy, ix = int(round(y)), int(round(x))
        if iy < 7 or ix < 7 or iy > ref.shape[0] - 8 or ix > ref.shape[1] - 8 or ref[iy, ix].max() >= 0.5 * float(es.sat):
            return np.tile([y, x], (3, 1))
        out = []
        for c in range(3):
            K = interp_nodes(np.asarray(es.psf_ref[c]["nodes"]), es.nodes, y, x).astype(np.float32)
            h = K.shape[-1] // 2
            D = ref[iy - 6:iy + 7, ix - 6:ix + 7, c]
            d = np.array([y - iy, x - ix], float)
            for _ in range(6):
                def model(dd):
                    Ks = cv2.warpAffine(K, np.float32([[1, 0, dd[1]], [0, 1, dd[0]]]), K.shape[::-1], flags=cv2.INTER_CUBIC)
                    return Ks[h - 6:h + 7, h - 6:h + 7]
                M0 = model(d)
                J = [(model(d + e) - model(d - e)) / 0.1 for e in (np.array([0.05, 0]), np.array([0, 0.05]))]
                A = np.stack([M0.ravel(), np.ones(M0.size), yyR.ravel(), xxR.ravel()], 1)
                coef, *_ = np.linalg.lstsq(A, D.ravel(), rcond=None)
                res = D.ravel() - A @ coef
                Jm = np.stack([coef[0] * J[0].ravel(), coef[0] * J[1].ravel()], 1)
                step, *_ = np.linalg.lstsq(Jm, res, rcond=None)
                d = d + np.clip(step, -0.3, 0.3)
                if np.abs(step).max() < 1e-3:
                    break
            d = np.clip(d, np.array([y - iy, x - ix]) - 1, np.array([y - iy, x - ix]) + 1)
            out.append([iy + d[0], ix + d[1]])
        return np.array(out)

    kept = []
    for x, y in zip(xs, ys):
        pos_c = fit_pos(x, y)                                  # (3, 2) per-channel (y, x)
        ly, lx = r * (y - y0) + origin, r * (x - x0) + origin
        cy, cx = int(round(ly)), int(round(lx))
        if cy - h < 0 or cx - h < 0 or cy + h + 1 > shape[0] or cx + h + 1 > shape[1]:
            continue
        e = np.arange(-h, h + 2) - 0.5                    # pixel edges relative to the stamp centre
        gy = np.diff(erf((e + cy - ly) / (np.sqrt(2) * sigma)))
        gx = np.diff(erf((e + cx - lx) / (np.sqrt(2) * sigma)))
        st = np.outer(gy, gx); st /= st.sum()
        iy_, ix_ = int(round(y)), int(round(x))
        R = int(np.ceil(ra)) + 3
        w = ref[max(iy_ - R, 0):iy_ + R + 1, max(ix_ - R, 0):ix_ + R + 1]
        yy, xx = np.mgrid[:w.shape[0], :w.shape[1]]
        rr = np.hypot(yy - (y - max(iy_ - R, 0)), xx - (x - max(ix_ - R, 0)))
        lvl = np.median(w[rr > ra + 1], 0) if (rr > ra + 1).any() else 0
        flux = np.maximum((w[rr <= ra] - lvl).sum(0), 1.0)
        if flux.sum() < min_flux:
            continue
        stamps.append(st.astype(np.float32)); iys.append(cy - h); ixs.append(cx - h); amps.append(flux.astype(np.float32))
        kept.append((y, x))
        offs.append([(r * (pc[0] - y0) + origin - cy, r * (pc[1] - x0) + origin - cx) for pc in pos_c])
        hal = star_halo(x, y) if r == 1 and halo else None
        halos.append(hal)
    if not stamps:
        return None
    out = {"stamps": np.stack(stamps), "iy": np.array(iys), "ix": np.array(ixs), "a": np.stack(amps),
           "off": np.array(offs), "sigma": float(sigma)}
    if any(h_ is not None for h_ in halos):
        hal = np.stack([h_ if h_ is not None else np.zeros((3, 2 * HR + 1, 2 * HR + 1), np.float32) for h_ in halos])
        # exposure-window pixel of each halo's top-left corner: star at window (y - y0, x - x0)
        cyx = [(int(round(y_ - y0)) - HR, int(round(x_ - x0)) - HR) for y_, x_ in kept]
        out.update({"halo": hal, "hy": np.array([c_[0] for c_ in cyx]), "hx": np.array([c_[1] for c_ in cyx])})
    return out


def smooth_background(es, r: int, origin: tuple[float, float], shape: tuple[int, int], fwhm: float) -> np.ndarray:
    """The smooth diffuse light for ImageMM's background term, (shape, 3) on the latent grid whose
    sample (0, 0) is at reference coordinate ``origin`` (sample j at origin + j / r).

    Plain ImageMM drives faint diffuse light to zero where the data cannot tell it from the wings
    of a nearby star: the fit folds it into the star's core and leaves the sky round every bright
    star empty.  On M 42 (DWARF 3) the restored sky sat 3-6 ADU below its surroundings out to 18 px
    round each bright star - a dark collar, in the null space of the blur (the restoration seen
    through its PSF matched the coadd within 2 ADU there).  Modelled as a separate smooth term, that
    light no longer competes with the stars.

    From the coadd with its sky model removed (the exposures' zero point), smoothed against its noise
    (Gaussian, 0.5 FWHM): the 25th percentile in cells 8 FWHM across (a 3 x 3 median over the cells
    against outliers), interpolated bicubically.  Stars and their halos cover a minority of a cell,
    so the percentile is the diffuse light under them, at or below the local level - it does not add
    light the data do not have; anything finer than a cell (stars, knots, filaments) stays entirely
    in the restored part.  Masking the stars and filling the holes instead left seams at the masks'
    edges, and an opening kept the bright stars' seeing halos (a glow round each)."""
    H0, W0 = es.ref.shape[:2]
    cell = max(int(round(8 * fwhm)), 8)
    pad = 2 * cell
    oy, ox = origin
    hy, wx = shape[0] / r, shape[1] / r
    ya, yb = int(np.floor(oy)) - pad, int(np.ceil(oy + hy)) + pad
    xa, xb = int(np.floor(ox)) - pad, int(np.ceil(ox + wx)) + pad
    src = (es.ref - es.sky_ref).astype(np.float32)
    win = np.stack([np.pad(src[max(ya, 0):min(yb, H0), max(xa, 0):min(xb, W0), c],
                           ((max(0, -ya), max(0, yb - H0)), (max(0, -xa), max(0, xb - W0))), mode="reflect")
                    for c in range(src.shape[-1])], -1)
    hh, ww = win.shape[0] // cell, win.shape[1] // cell
    out = np.empty_like(win)
    for c in range(win.shape[-1]):
        z = cv2.GaussianBlur(win[..., c], (0, 0), max(0.5 * fwhm, 0.5))
        grid = np.percentile(z[:hh * cell, :ww * cell].reshape(hh, cell, ww, cell), 25, axis=(1, 3)).astype(np.float32)
        grid = cv2.medianBlur(grid, 3) if min(hh, ww) >= 3 else grid
        # cell centres at (i + 0.5) cell: resize maps them there with pixel-centre alignment
        full = cv2.resize(grid, (ww * cell, hh * cell), interpolation=cv2.INTER_CUBIC)
        out[..., c] = np.pad(full, ((0, win.shape[0] - hh * cell), (0, win.shape[1] - ww * cell)), mode="edge")
    out = np.maximum(out, 0)
    # onto the latent grid: sample j at reference oy + j / r, i.e. window pixel (oy - ya) + j / r
    M_ = np.float32([[1.0 / r, 0, ox - xa], [0, 1.0 / r, oy - ya]])
    return cv2.warpAffine(out, M_, (shape[1], shape[0]), flags=cv2.INTER_LINEAR | cv2.WARP_INVERSE_MAP,
                          borderMode=cv2.BORDER_REFLECT)


def n2n_pass(xa: np.ndarray, xb: np.ndarray, iters: int = 2000, patch: int = 128, batch: int = 16,
             device=None, progress=None, cancel=None, seed: int = 0) -> tuple[np.ndarray, dict]:
    """Noise2Noise (Lehtinen et al. 2018) on two ImageMM restorations of disjoint sets of
    subs, whose noise is therefore independent.

    A network f is trained to minimise E w(x_A) |f(x_A) - x_B|^2 (and with A and B swapped).
    With x_B independent of x_A given the sky, the minimiser is E[x_B | x_A]; the loss is
    taken on the *linear* values (an L2 loss on transformed targets would give E[g(x_B)],
    biased for faint signal), and the weights w depend only on the input, so they change
    which errors dominate training but not the minimiser.  The network sees the inputs
    through u = asinh(x / (3 s)) and predicts in that domain, mapped back to linear values
    for the loss.  s: robust noise scale of (x_A - x_B)/sqrt 2 over the pixels where *both*
    restorations carry signal (min(x_A, x_B) above 1e-3 of the 99th percentile).  ImageMM
    drives the sky to ~0 - on IC 405 more than half of all latent pixels - so any scale that
    includes the sky (the former "above the median" selection) collapses to ~1e-4 of the real
    noise; the loss weights 1 / (1 + (x/k)^2) then silenced every source pixel and the network
    returned values at the clamp (~2e6 over the whole nebula).
    Returns (1/2 (f(x_A) + f(x_B)), info with "residual" 1/2 (f(x_A) - f(x_B)))."""
    from .denoise import UNet, _autocast, infer
    device = device or pick_device()
    rng = np.random.default_rng(seed)
    torch.manual_seed(seed)
    C = xa.shape[2]
    s = np.zeros(C, np.float32)
    for c in range(C):
        a, b = xa[..., c], xb[..., c]
        sig = 0.5 * (a + b)
        thr = 1e-3 * float(np.percentile(sig, 99))
        on = np.minimum(a, b) > thr
        if on.sum() < 1000:                    # almost empty channel: every pixel with any signal
            on = sig > thr
        d = (a - b)[on] if on.any() else (a - b).ravel()
        s[c] = 1.4826 * np.median(np.abs(d - np.median(d))) / np.sqrt(2)
        # floor: a tenth of the scale on the brightest tenth of the pixels, which always carry signal.
        # With ImageMM's background term the restored part is 0 on >90 % of the pixels and most pixels
        # "with signal" in both halves were at the threshold, so the MAD came out 0 (M 42, red and
        # blue), k ~ 0, and the network's output ran to the clamp - 24 000 pixels above 1e5 ADU
        bright = sig >= np.percentile(sig, 90)
        db = (a - b)[bright]
        s_b = 1.4826 * np.median(np.abs(db - np.median(db))) / np.sqrt(2)
        s[c] = max(s[c], 0.1 * s_b)
        if not s[c] > 0:
            s[c] = float(np.std(a - b)) / np.sqrt(2)
    s = np.maximum(s, 1e-12)
    k = 3 * s
    fwd = lambda x: np.arcsinh(x / k).astype(np.float32)
    ua, ub = fwd(xa), fwd(xb)
    # predictions are mapped back with sinh, which overflows float32 beyond ~89: bound them to
    # the range the data span in this domain (with a margin), beyond which they mean nothing
    u_lo = float(min(ua.min(), ub.min())) - 1.0
    u_hi = float(max(ua.max(), ub.max())) + 1.0
    ta = torch.from_numpy(np.ascontiguousarray(np.moveaxis(xa, -1, 0)))
    tb = torch.from_numpy(np.ascontiguousarray(np.moveaxis(xb, -1, 0)))
    tua = torch.from_numpy(np.ascontiguousarray(np.moveaxis(ua, -1, 0)))
    tub = torch.from_numpy(np.ascontiguousarray(np.moveaxis(ub, -1, 0)))
    kt = torch.from_numpy(k).view(1, C, 1, 1).to(device)
    net = UNet(ch=C).to(device)
    opt = torch.optim.Adam(net.parameters(), lr=3e-4)
    sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=1e-3, total_steps=iters, pct_start=0.15)
    h, w = xa.shape[:2]
    t0 = time.time()
    for it in range(iters):
        if cancel and cancel():
            raise RuntimeError("cancelled")
        ys = rng.integers(0, h - patch, batch)
        xs = rng.integers(0, w - patch, batch)
        inp, tgt, lin_in = [], [], []
        for y0, x0, sw in zip(ys, xs, rng.random(batch) < 0.5):
            src = (tub, ta, tb) if sw else (tua, tb, ta)
            rot, fl = int(rng.integers(0, 4)), rng.random() < 0.5
            parts = []
            for z in src:
                q = torch.rot90(z[:, y0:y0 + patch, x0:x0 + patch], rot, (1, 2))
                parts.append(q.flip(2) if fl else q)
            inp.append(parts[0]), tgt.append(parts[1]), lin_in.append(parts[2])
        inp, tgt, lin_in = (torch.stack(z).to(device) for z in (inp, tgt, lin_in))
        with _autocast(device):
            u = net(inp)
        pred = torch.sinh(u.float().clamp(u_lo, u_hi)) * kt     # linear prediction
        wgt = 1.0 / (1.0 + (lin_in / kt) ** 2)                   # depends on the input only
        loss = (wgt * (pred - tgt) ** 2).mean()
        if not torch.isfinite(loss):
            raise RuntimeError(f"ImageMM Noise2Noise pass: the training loss is not finite at step {it}")
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(net.parameters(), 1.0)
        opt.step()
        sched.step()
        if progress and (it % 25 == 0 or it == iters - 1):
            progress(it + 1, iters, f"ImageMM Noise2Noise pass {it + 1}/{iters} ({time.time() - t0:.0f}s)")
    net.eval()
    tta = 8 if device.type != "cpu" else 2
    back = lambda u: np.sinh(np.clip(u, u_lo, u_hi)) * k
    fa, fb = back(infer(net, ua, tta=tta)), back(infer(net, ub, tta=tta))
    out = 0.5 * (fa + fb)
    bad = int((~np.isfinite(out)).sum())
    if bad:
        raise RuntimeError(f"ImageMM Noise2Noise pass: {bad} non-finite pixels in the output")
    # the output's own noise: f(x_A) and f(x_B) err independently (disjoint subs), so 1/2 (f(x_A) - f(x_B))
    # has the variance of 1/2 (f(x_A) + f(x_B))'s error, and its structure (correlated, after the
    # deconvolution and the network).  The display's denoising is calibrated on it (postprocess).
    resid = (0.5 * (fa - fb)).astype(np.float32)
    # where the network had no training signal - the loss weight 1 / (1 + (x/k)^2) is ~0 far above the
    # noise: star cores - the plain mean of the two restorations instead of its output (their noise is
    # independent, so the mean already halves it, and it is negligible at that signal), as the stack's
    # denoiser hands its bright pixels back (denoise.n2n_restore, the same ramp in asinh units of 3 sigma:
    # ~50 to ~220 sigma).  Untrained there, the network's output was arbitrary: M 42's bright cores came
    # out ~35 % too green against both halves (2026-10-07), cyan in the HOO palette
    from scipy.ndimage import maximum_filter
    mean = 0.5 * (xa + xb)
    g = maximum_filter(np.abs(np.arcsinh(mean / k)).max(-1, keepdims=True), size=(5, 5, 1))
    keep = np.clip((g - 3.5) / 1.5, 0, 1).astype(np.float32)
    out = out * (1 - keep) + mean * keep
    resid = (resid * (1 - keep) + 0.5 * (xa - xb) * keep).astype(np.float32)
    return out.astype(np.float32), {"noise_scale": s.tolist(), "iters": iters, "residual": resid}


# ----------------------------------------------------------------- full restoration
def superresolved_kernels(K: np.ndarray, r: int, sigma: float, device=None, progress=None):
    """Eq. 11 for every exposure and channel: (n, C, d', d') -> (n, C, r d', r d'), divided by r^2.
    Also accepts field-grid node kernels (n, C, ny, nx, d', d').

    With D the r x r *average*, D(h * g_sigma) = f makes h sum to r^2, and the latent x of
    D(h * x) is in flux per latent pixel (1/r^2 of the exposures' surface brightness).  The
    kernels h / r^2 describe exactly the same model for r^2 x, so with them the latent is in
    the exposures' (and the stack's) surface-brightness units - which the initial guess, the
    stack-grid forward model of the network and the pipeline all assume."""
    lead, d = K.shape[:-2], K.shape[-1]
    N = int(np.prod(lead))
    if progress:
        progress(0, 1, f"ImageMM: solving Eq. 11 for {N} PSFs (r = {r}, sigma = {sigma})")
    h, mse = refine_psfs(K.reshape(N, d, d), r, sigma, device=device)
    return h.reshape(*lead, r * d, r * d) / r ** 2, mse


def choose_sigma(K: np.ndarray, r: int, sigma: float, device=None, step: float = 0.1, max_sigma: float = 2.5,
                 min_peak: float = 0.9) -> tuple[float, dict]:
    """The latent resolution actually usable for these PSFs: the smallest sigma >= ``sigma`` (in steps
    of ``step``) at which the Eq. 11 kernels h of a sample of the PSFs ``K`` (n, C, k, k) are
    peaked - median over the sample and every channel of h(centre) / max(h) >= ``min_peak``.

    Why: Eq. 11 asks for h >= 0 with D(h * g_sigma) = f.  When the PSF's core is flatter than the
    Gaussian g_sigma (a boxy core: the M 31 set's optical low-pass / sampling response, centre /
    first ring 1.2 against a Gaussian's 1.3-1.6), the only non-negative solution is a ring-shaped
    h - zero at the centre, its weight at r = 1 - and the restoration then carries that ring round
    every star and a 2-px texture over the whole field (M 31 at sigma = 1: rings to 50 px; at 1.3
    clean).  The paper's sigma = 1 presumes PSFs broader and smoother than that; a sharper or boxy
    PSF cannot be restored to it.  Returns (sigma, {"requested", "chosen", "peak": per-channel
    centre/max at the chosen sigma})."""
    n, C = K.shape[:2]
    pick = np.linspace(0, n - 1, min(n, 24)).round().astype(int)
    Ks = K[pick]
    sig = float(sigma)
    peaks = None
    while True:
        h, _ = superresolved_kernels(Ks, r, sig, device=device)
        k = h.shape[-1]
        c = k // 2
        centre = h[..., c, c]
        mx = h.reshape(*h.shape[:2], -1).max(-1)
        peaks = [float(np.median(centre[:, ch] / np.maximum(mx[:, ch], 1e-30))) for ch in range(C)]
        if min(peaks) >= min_peak or sig + step > max_sigma + 1e-9:
            break
        sig = round(sig + step, 3)
    return sig, {"requested": float(sigma), "chosen": sig, "peak": peaks}


def unit_sum(k: np.ndarray) -> np.ndarray:
    """Kernels (..., k, k) scaled to unit sum: a PSF conserves flux.  The Eq. 11 solve does not
    guarantee it - its non-negativity projection adds mass wherever the exact h would go negative,
    most in the field's corners (M 42, 2026-10-06: sums 1.0002 at the centre to 1.010 in a corner,
    1.043 for single subs).  A sum of 1 + e scales the whole restoration by 1 / (1 + e), and on the
    sky pedestal (``mm_restore``) that is a sky offset of -P e, constant over each cutout because
    its kernels are taken at the cutout's centre: steps of up to 55 ADU between cutouts."""
    s = k.sum(axis=(-2, -1), keepdims=True)
    return (k / np.where(s > 0, s, 1.0)).astype(np.float32)


def field_kernels(es, idx: list[int], r: int, sigma: float | None, psf_model: str, device=None, progress=None,
                  cache: str | None = None) -> tuple[np.ndarray, dict | None]:
    """Latent-grid kernels of the exposures ``idx`` at the nodes of the field PSF grid
    ``es.nodes``: (n, C, ny, nx, k, k) - the measured PSFs f(t), or with r > 1 or a sigma the
    Eq. 11 kernels h(t) solved at every node.  Kernels for a cutout are interpolated
    bilinearly between the nodes (exposures.interp_nodes).  ``cache``: file for the Eq. 11
    solution (it takes minutes), reused while the exposures, r, sigma and the model match."""
    K = es.node_kernels(idx, psf_model)
    if not (r > 1 or sigma is not None):
        return unit_sum(K), None
    sigma = 1.1 if sigma is None else sigma
    # the resolution these PSFs can be restored to (choose_sigma): tried on the kernels of the central
    # node before the full solve
    ny, nx = K.shape[2], K.shape[3]
    if progress:
        progress(0, 1, f"ImageMM: checking the latent resolution (sigma = {sigma})")
    sigma_eff, chosen = choose_sigma(K[:, :, ny // 2, nx // 2], r, sigma, device=device)
    if progress and sigma_eff != sigma:
        progress(0, 1, f"ImageMM: latent resolution raised to sigma = {sigma_eff} (the PSF's core is flatter than g_{sigma})")
    sigma = sigma_eff
    import hashlib
    import pickle
    key = hashlib.sha1(np.ascontiguousarray(K).tobytes() + f"{r}|{sigma}".encode()).hexdigest()
    if cache and os.path.exists(cache):
        try:
            with open(cache, "rb") as f:
                c = pickle.load(f)
            if c.get("key") == key:
                return _normalised(c["kernels"], c["eq11"])
        except Exception:
            pass
    kern, mse = superresolved_kernels(K, r, sigma, device=device, progress=progress)
    eq11 = {"sigma": sigma, "sigma_requested": chosen["requested"], "kernel_peak": chosen["peak"],
            "mse_max": float(mse.max()), "mse_median": float(np.median(mse))}
    if cache:
        os.makedirs(os.path.dirname(cache), exist_ok=True)
        with open(cache, "wb") as f:
            pickle.dump({"key": key, "kernels": kern, "eq11": eq11}, f, protocol=4)
    return _normalised(kern, eq11)


def _normalised(kern: np.ndarray, eq11: dict) -> tuple[np.ndarray, dict]:
    """The Eq. 11 kernels at unit sum (``unit_sum``), with the correction recorded."""
    s = kern.sum(axis=(-2, -1))
    eq11 = {**eq11, "sum_before_normalising": [round(float(s.min()), 5), round(float(np.median(s)), 5),
                                               round(float(s.max()), 5)]}
    return unit_sum(kern), eq11


def restore(es, r: int = 1, sigma: float | None = None, psf_model: str = "empirical", n_groups: int = 0,
            robust: bool = True, delta: float = 2.0, kappa: float = 2.0, epsilon: float = 1e-6,
            max_iters: int = 1000, accelerate: bool = False, stop: str = "c15", tile: int = 384, device: str = "auto",
            n2n: bool = False, n2n_iters: int = 2000, min_iters: int = 0, kernel_cache: str | None = None,
            halves: np.ndarray | None = None, background: bool = False,
            region: tuple[int, int, int, int] | None = None, progress=None, cancel=None) -> tuple[np.ndarray, dict]:
    """ImageMM over the whole field of the prepared exposures ``es`` (exposures.ExposureSet).

    r = 1 and sigma None: Algorithm 1 (robust=False) / 3 (robust=True) with the measured
    PSFs f(t).  r > 1, or a sigma: Algorithm 2 with the Eq. 11 kernels (the paper uses
    sigma = 1.1 for r = 2 and sigma = 1 for r = 1; default here 1.1 when r > 1).
    The field is restored in overlapping cutouts, as the paper processes cutouts; each is a
    complete ImageMM problem with its own padded latent (so flux from just outside the
    cutout is modelled) and its own Eq. C15 stop.  Cutouts overlap by at least two kernel
    widths and are blended with feathered weights.
    ``n2n``: restore the two halves of the subs separately (disjoint data, independent noise;
    ``halves``: 0 / 1 per exposure of ``es`` from ``analysis.half_split``, default even / odd)
    and combine them with ``n2n_pass`` instead of restoring all subs at once.
    ``region``: (y0, y1, x0, x1) of the reference grid to restore instead of the whole field
    (previews, experiments); the result then covers that window only.
    Returns (latent image on the r x finer grid - sample j at reference coordinate j / r
    (relative to the region's origin) -, info with the coverage map, per-cutout convergence and,
    with ``n2n``, the output's noise realisation "residual" (n2n_pass))."""
    dev = device if isinstance(device, torch.device) else pick_device(device)
    t0 = time.time()

    def _iteration_check(k, crit):
        # ``cancel`` is the job's checkpoint: it waits while the job is paused, so a pause takes
        # effect within one iteration instead of after the whole cutout
        if cancel and cancel():
            raise RuntimeError("cancelled")
    from .exposures import interp_nodes
    idx = es.usable()
    # the PSF of each exposure where a cutout is: field-grid node kernels, interpolated per cutout
    kern, eq11 = field_kernels(es, idx, r, sigma, psf_model, device=dev, progress=progress, cache=kernel_cache)
    ks = kern.shape[-1]
    RY0, RY1, RX0, RX1 = region if region is not None else (0, es.H0, 0, es.W0)
    RY0, RX0 = max(0, int(RY0)), max(0, int(RX0))
    RY1, RX1 = min(es.H0, int(RY1)), min(es.W0, int(RX1))
    H0, W0 = RY1 - RY0, RX1 - RX0
    overlap = int(max(64, 2 * math.ceil(ks / r)))
    tile = max(tile, 3 * overlap)
    # the exposures of a cutout (y, v, mask) must fit on the device next to at least one
    # exposure's temporaries; otherwise use smaller cutouts (same overlap, so the same result
    # up to the blending of more seams - see test_tiling in experiments/test_imagemm.py)
    free = free_device_memory(dev)
    if not n2n:
        sets = [np.arange(len(idx))]
    elif halves is not None:
        h = np.asarray(halves)[idx]
        sets = [np.flatnonzero(h == 0), np.flatnonzero(h == 1)]
    else:
        sets = [np.arange(0, len(idx), 2), np.arange(1, len(idx), 2)]
    n_exp = max(len(q) for q in sets)
    n_exp = min(n_exp, n_groups) if n_groups else n_exp
    if free is not None:
        def need(t):              # bytes: exposures of the cutout + one chunk + ~12 latent-size arrays
            return 4 * 3 * t * t * (_PERSISTENT * n_exp + _PER_CHUNK) + 4 * 3 * (t * r + ks) ** 2 * 12
        while tile > 3 * overlap and need(tile) > 0.85 * free:
            tile = max(3 * overlap, int(tile * 0.85))
        if need(tile) > 0.85 * free:
            raise RuntimeError(
                f"not enough {dev.type.upper()} memory for ImageMM: {free / 2**30:.2f} GiB free, one "
                f"{tile} px cutout of {n_exp} exposures needs {need(tile) / 2**30:.2f} GiB. Another process may be "
                f"holding GPU memory (check nvidia-smi), or use seeing groups / another device.")
    step = tile - overlap
    ys = sorted({min(y, max(H0 - tile, 0)) for y in range(0, max(H0 - overlap, 1), step)})
    xs = sorted({min(x, max(W0 - tile, 0)) for x in range(0, max(W0 - overlap, 1), step)})
    outs, tiles = [], []
    cov = np.zeros((H0 * r, W0 * r, 3), np.float32)
    ntot = len(ys) * len(xs) * len(sets)
    for part, sel in enumerate(sets):
        sub_idx = [idx[i] for i in sel]
        out = np.zeros((H0 * r, W0 * r, 3), np.float32)
        acc = np.zeros((H0 * r, W0 * r, 1), np.float32)
        if part == 0 and background:
            bgmap = np.zeros((H0 * r, W0 * r, 3), np.float32)
        for y0 in ys:
            for x0 in xs:
                if cancel and cancel():
                    raise RuntimeError("cancelled")
                y1, x1 = min(y0 + tile, H0), min(x0 + tile, W0)
                sub_kern = interp_nodes(kern[sel], es.nodes, RY0 + (y0 + y1 - 1) / 2,
                                        RX0 + (x0 + x1 - 1) / 2).astype(np.float32)
                x, info = restore_cutout(es, RY0 + y0, RY0 + y1, RX0 + x0, RX0 + x1, idx=sub_idx, r=r, kernels=sub_kern, robust=robust,
                                         psf_model=psf_model, n_groups=n_groups, device=dev, delta=delta,
                                         kappa=kappa, epsilon=epsilon, max_iters=max_iters, accelerate=accelerate,
                                         stop=stop, min_iters=min_iters, log=_iteration_check, background=background)
                wy = _edge_weights((y1 - y0) * r, overlap * r, y0 > 0, y1 < H0)
                wx = _edge_weights((x1 - x0) * r, overlap * r, x0 > 0, x1 < W0)
                wgt = np.outer(wy, wx)[..., None]
                sl = (slice(y0 * r, y1 * r), slice(x0 * r, x1 * r))
                out[sl] += x * wgt
                if part == 0 and background and "background" in info:
                    bgmap[sl] += info["background"] * wgt
                cov[sl] += info["coverage"] * wgt / len(sets)
                acc[sl] += wgt
                tiles.append({"set": part, "window": [RY0 + y0, RY0 + y1, RX0 + x0, RX0 + x1], "iterations": info["iterations"],
                              "converged": info["converged"], "saturated_pixels": info.get("saturated_pixels", 0)})
                if progress:
                    done = len(tiles)
                    progress(done, ntot, f"ImageMM: cutout {done}/{ntot} "
                                         f"({info['iterations']} iterations, {time.time() - t0:.0f}s)")
        outs.append(out / np.maximum(acc, 1e-12))
        if part == 0:
            acc0 = acc
            if background:
                bgmap /= np.maximum(acc, 1e-12)
    cov /= np.maximum(acc0, 1e-12)
    n2n_info, resid = None, None
    if not background:
        bgmap = None
    if n2n:
        # on the restored part only: the background term is the same map in both halves, so their
        # difference - the noise scale the pass is normalised by - collapsed to ~0 wherever it
        # dominated, and the network returned garbage (M 42: 1e5 ADU over the whole region)
        b_ = bgmap if background else 0.0
        out, n2n_info = n2n_pass(outs[0] - b_, outs[1] - b_, iters=n2n_iters, device=dev, progress=progress, cancel=cancel)
        out = out + b_
        resid = n2n_info.pop("residual")
    else:
        out = outs[0]
    if dev.type == "mps":
        torch.mps.empty_cache()
    elif dev.type == "cuda":
        torch.cuda.empty_cache()
    bad = int((~np.isfinite(out)).sum())
    if bad:                       # never save (and later render) a restoration with NaN / inf pixels
        raise RuntimeError(f"ImageMM restoration: {bad} non-finite pixels ({bad / out.size:.2%}) in the result")
    return out, {"method": "ImageMM (arXiv:2501.03002), Algorithm " + ("2" if eq11 is not None else ("3" if robust else "1")),
                 "robust": robust, "delta": delta, "kappa": kappa, "epsilon": epsilon, "stop": stop, "r": r, "eq11": eq11,
                 "psf_model": psf_model, "n_groups": n_groups, "accelerate": accelerate, "n2n": n2n_info,
                 "n_exposures": len(idx), "psf_size": ks, "tiles": tiles, "coverage": cov, "residual": resid,
                 "saturated_pixels": int(sum(t.get("saturated_pixels", 0) for t in tiles)),
                 "fwhm": float(getattr(es, "fwhm_ref", (ks / r - 1) / 7)) * r,      # seeing FWHM, latent pixels
                 "seconds": round(time.time() - t0, 1)}
